### ISSUE TITLE
Collection Edit page multiplies "X Remove" controls

### ISSUE THREAD

**Issue by atz** [projecthydra-labs/hyrax#1018]
- View a collection, looks OK-ish, Title displays with 1 "X Remove" control
- Click "Browse View"
- Click "Back" button: there are now 3 attribute red "X Remove" controls
- Repeat, now 6 controls, crowding out the Title itself!

In screenshots:
![screen shot 2017-05-22 at 5 48 12 pm](https://cloud.githubusercontent.com/assets/109954/26334043/0bf958c2-3f17-11e7-9e9f-c9de73805177.png)
----------------------------
![screen shot 2017-05-22 at 5 48 33 pm](https://cloud.githubusercontent.com/assets/109954/26334044/0bfa8d00-3f17-11e7-955c-99f0490272f9.png)
----------------------------
![screen shot 2017-05-22 at 5 48 53 pm](https://cloud.githubusercontent.com/assets/109954/26334042/0bf8be62-3f17-11e7-80e9-6b3076505f88.png)

Series expansion for `n` page loads is:
`1 3 6 10 15 21 ...` 

Which is to say the delta in the number of additional controls rendered each step is:
`1 2 3 4 5 6 ... n`

So something in global JS is getting added to with each load.

**Comment by jcoyne** [comment]
The same can happen on create a new work:
<img width="738" alt="screen shot 2017-05-22 at 10 19 30 pm" src="https://cloud.githubusercontent.com/assets/92044/26337216/cf40cdb8-3f3c-11e7-83f5-3d90fc6a4edf.png">

**Comment by jcoyne** [comment]
Fixed with hydra-editor 3.3.2.
