### ISSUE TITLE
Sufia Migration to Hyrax: Instructions about Static Pages

### ISSUE THREAD

**Issue by metageeky** [projecthydra-labs/hyrax#1033]
### Descriptive summary

This applies to all version of Hyrax. When migrating from Sufia to Hyrax, static pages need to be moved from `/app/views/static` to `/app/views/hyrax/static`. No changes need to be made to how you add routes. 

### Rationale

It isn't completely obvious from the migration notes where those files go. 

### Related work

[https://github.com/projecthydra-labs/hyrax/issues/4](https://github.com/projecthydra-labs/hyrax/issues/4)

https://github.com/projecthydra-labs/hyrax/releases/tag/v1.0.0.rc2

**Comment by mjgiarlo** [comment]
Added to release notes. Thank you, @metageeky!
