### ISSUE TITLE
Migration doesn't work on Postgres

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyrax#1035]
```
 $ rake db:migrate
== 20170524170114 ChangeChecksumAuditLog: migrating ===========================
-- rename_column(:checksum_audit_logs, :version, :checked_uri)
   -> 0.0321s
-- change_column(:checksum_audit_logs, :pass, :boolean)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DatatypeMismatch: ERROR:  column "pass" cannot be cast automatically to type boolean
HINT:  You might need to specify "USING pass::boolean".
: ALTER TABLE "checksum_audit_logs" ALTER COLUMN "pass" TYPE boolean
/Users/jcoyne/workspace/hyku/db/migrate/20170524170114_change_checksum_audit_log.hyrax.rb:5:in `change'
ActiveRecord::StatementInvalid: PG::DatatypeMismatch: ERROR:  column "pass" cannot be cast automatically to type boolean
HINT:  You might need to specify "USING pass::boolean".
: ALTER TABLE "checksum_audit_logs" ALTER COLUMN "pass" TYPE boolean
/Users/jcoyne/workspace/hyku/db/migrate/20170524170114_change_checksum_audit_log.hyrax.rb:5:in `change'
PG::DatatypeMismatch: ERROR:  column "pass" cannot be cast automatically to type boolean
HINT:  You might need to specify "USING pass::boolean".
/Users/jcoyne/workspace/hyku/db/migrate/20170524170114_change_checksum_audit_log.hyrax.rb:5:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by jrochkind** [comment]
Oops. Weird, that's not good. Hmm, not sure how to fix it. How do you change a column type to boolean in a way that will work on postgres?

**Comment by jrochkind** [comment]
There's a way to write a postgres-specific migration... but I can't find any way to write a generic migration that will also work on postgres. 

Hmm. Maybe add the new column, put something in the migration to move the data over in a db-independent way somehow, then drop the new column. Does that seem reasonable?

**Comment by jcoyne** [comment]
Yes, unfortunately I think I'll have to do something like that

**Comment by jrochkind** [comment]
I can try to fix the migration and PR. I'll just fix the existing migration in place. People who already have copied it into local app may have to re-copy migration.

**Comment by jrochkind** [comment]
the migration was trying to change column name too in same migration, conveniently.

**Comment by jrochkind** [comment]
Oh, the fixity improvements DID somehow make it into 1.0?  I thought you told me I'd have to backport it myself it was going to! Oops, guess the bad migration got into a release then, sorry.
