### ISSUE TITLE
Add sharing to collections

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra-labs/hyrax#128]
<a href="https://github.com/elrayle"><img src="https://avatars.githubusercontent.com/u/6855473?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [elrayle](https://github.com/elrayle)**
_Thursday May 05, 2016 at 18:52 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/1988_

----

#### Descriptive summary

Sufia 7.0.beta
##### Expected behavior

New feature: Add sharing for collections.  Depositor can share read/edit privileges with other users/groups.  For editing, this allows the sharee to perform all editing functionality for the collection including changing metadata for the collection, adding/removing works from the collection, deleting the collection.  This does _not_ modify permissions for any members of the collection.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Monday May 09, 2016 at 16:01 GMT_

----

If this is ready in time for the 7.0.0 release, great! :clap: Otherwise, I'm not inclined to make this a blocker.

**Comment by jonathandixon** [comment]
I'm looking to pick up this issue. Is that cool?

Unless I'm missing something, this should be pretty easy to implement. The Collection behavior already includes the `Hyrax::Permissions` module and the Blacklight searches seem to honor share permissions added to Collections (preliminary testing done in my hyrax based app). 

There are questions surrounding the form UI:
- Should the "Share with" section of the form resemble the FileSet version or the Work (base) version? 
- Should the Collection form be broken up into tabs, similar to FileSets and Works? (Maybe this would be a separate issue.)

**Comment by hackmastera** [comment]
@jonathandixon do it! 👏 

I don't have strong feelings on either question, really, and would err on the side of "whatever makes it easier to get it done". My instinct would be to model off the work form since that code is probably newer. Also I expect the users will see the work form a lot more frequently than they would see a fileset form, so using the work form will result in greater consistency of user experience.

**Comment by jonathandixon** [comment]
Great, thanks! My employer and I are working on the Contributor License Agreement. 
I'll begin working on this, but I don't have permission to assign this issue to me.

**Comment by mjgiarlo** [comment]
@jonathandixon Can you say more about how you'll be using collections before you proceed? I ask primarily because the collections situation is more complex now -- with collections and administrative sets both implemented and display sets currently being discussed -- than it was when this ticket was written up. 

If you have any questions about CLAs, feel free to drop me a line, btw, and glad to see you diving into Hydra!

**Comment by jonathandixon** [comment]
@mjgiarlo Essentially all I will be doing is adding the share form to the new/edit collection form. The collection model already includes `Hyrax:Permissions` and the blacklight searches and cancan abilities already enforce those permissions. 

This may be my lack of experience with Hydra talking, but I don't see this having an effect on admin sets. I would think display sets would also benefit from having share options as well.

**Comment by mjgiarlo** [comment]
@jonathandixon Sorry, what I meant was: how do you expect to be using shareable collections within your Hyrax application? What's the use case?

I ask because as administrative sets and display sets have become better defined, questions have been raised about the utility of collections. Collections have been used as a facsimile for these other sets in the past because they are what we had. My understanding is that our current collections implementation is primarily useful as a way for individual users to organize and group content. What are the use cases for sharing such a user collection?

**Comment by jonathandixon** [comment]
@mjgiarlo In short, we are using Hyrax as a publication management system. We intend to use collections just as you have mentioned, "as a way for individual users to organize and group content". I can see our users (i.e. researchers) wanting to create a collection that they can then share with collaborators or administrative assistants or even funding sponsors, but not make available to the public or institute as a whole.

Does that help? Are you thinking this feature will no longer be of interest to the hyrax community?

**Comment by mjgiarlo** [comment]
@jonathandixon Yes, that helps and your use case is perfect for collections. Carry on! Thanks for indulging my questions. 😄  I'll slot this ticket into the 1.0.0 milestone, and keep an eye out for your CLAs in the meantime.

**Comment by jonathandixon** [comment]
FYI: I have this coded up and tested, but It could be a few weeks for the CLAs to come through.

**Comment by mjgiarlo** [comment]
@jonathandixon Great!

If you'd like, you can create your PR in advance of the CLAs so that we can start the code review process, and I will mark the PR as "blocked" until the CLAs are good to go.

**Comment by jonathandixon** [comment]
@mjgiarlo Thanks

I would love to create the PR and start the code review. But with all the legal stuff (IP disclosures and CLAs) I'd feel better waiting. I'm even afraid to push the code to my forked repo.

**Comment by mjgiarlo** [comment]
@jonathandixon No problem.
