### ISSUE TITLE
Create a Review Queue Index Page

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra-labs/hyrax#168]
<a href="https://github.com/vantuyls"><img src="https://avatars.githubusercontent.com/u/9534576?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vantuyls](https://github.com/vantuyls)**
_Thursday Sep 01, 2016 at 23:00 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2618_

----

Review Queue Index Page shows objects that are in the Inactive Object State (ie objects needing to be published) and waiting review to become active.

Page should include:
- [x] Item Title
- [ ] Item ID (?)
- [x] Status
- [ ] Name of Workflow item was deposited into
- [ ] Workflow step the item is at (e.g. 2 of 3)

Decomposes #2426 and #2445

**Comment by mjgiarlo** [comment]
<a href="https://github.com/vantuyls"><img src="https://avatars.githubusercontent.com/u/9534576?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vantuyls](https://github.com/vantuyls)**
_Wednesday Sep 14, 2016 at 18:33 GMT_

----

mockups of review queue index page are here:
https://docs.google.com/presentation/d/1uMDxYuSfUr9kFswb4HzkQzYYgefL6oaZOAAmCoCQxl4/edit?usp=sharing

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Friday Oct 28, 2016 at 22:56 GMT_

----

Defer until 1+-step workflow work starts.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/vantuyls"><img src="https://avatars.githubusercontent.com/u/9534576?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vantuyls](https://github.com/vantuyls)**
_Friday Oct 28, 2016 at 22:58 GMT_

----

also - refer to any recent Lerna UI mockups or ping @ggeisler for thoughts/suggestions/new mockups

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcoyne](https://github.com/jcoyne)**
_Saturday Oct 29, 2016 at 00:46 GMT_

----

This is already done except for "Workflow step the item is at (e.g. 2 of 3)", which is impossible due to workflows not necessarily being linear.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Monday Oct 31, 2016 at 14:24 GMT_

----

True. Maybe we can list the workflow step as the name of the state the item is currently in?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcoyne](https://github.com/jcoyne)**
_Monday Oct 31, 2016 at 14:55 GMT_

----

@mjgiarlo that's a fine solution.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Monday Oct 31, 2016 at 15:02 GMT_

----

@vantuyls if you're cool with that idea, can you reflect the change in your mock-ups above?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/vantuyls"><img src="https://avatars.githubusercontent.com/u/9534576?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vantuyls](https://github.com/vantuyls)**
_Friday Nov 04, 2016 at 15:53 GMT_

----

yep - will update mockups.

**Comment by jcoyne** [comment]
@vantuyls @mjgiarlo  is this done? The mockups here conflict with the mockups @ggeisler did.

**Comment by mjgiarlo** [comment]
@vantuyls Does the work merged in https://github.com/projecthydra-labs/hyrax/pull/348 satisfy the requirements for this issue?

**Comment by vantuyls** [comment]
yessir. looks good to me.

**Comment by mjgiarlo** [comment]
Thanks! Closing. Closed in #348.
