### ISSUE TITLE
The inactive state of mediated deposit workflow supersedes the visibility settings for the object

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra-labs/hyrax#176]
<a href="https://github.com/blancoj"><img src="https://avatars.githubusercontent.com/u/11095558?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [blancoj](https://github.com/blancoj)**
_Wednesday Sep 21, 2016 at 17:25 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2728_

----

When mediated deposit is enabled, and a work is in inactive state because it is in the mediated deposit workflow and has not yet been approved, but the work has been marked as visible to other user(s), the work should not be visible by those user(s) and those user(s) should not yet receive a notification that the work is available.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Friday Oct 28, 2016 at 22:18 GMT_

----

@vantuyls and I believe this is a better ticket for CC, since this is not mediated deposit-centric. @jcoyne confirm/deny?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Friday Nov 04, 2016 at 21:57 GMT_

----

@vantuyls Should we defer this to Phase 2, operating under the assumption that Phase 1 is for 0-step?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Monday Dec 05, 2016 at 17:42 GMT_

----

@vantuyls how much do we really care about this one? I'm moving it to phase 2 for now, but it'd be good to see if this is still relevant and highly desired. (I wonder if this can collapse into the "editing an object sends it back through workflow" story?)

**Comment by mjgiarlo** [comment]
<a href="https://github.com/vantuyls"><img src="https://avatars.githubusercontent.com/u/9534576?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vantuyls](https://github.com/vantuyls)**
_Monday Dec 05, 2016 at 18:19 GMT_

----

If we're sure that the object will remain hidden from view when it is in the workflow, then OK. Otherwise, this needs to be an issue we address explicitly.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Monday Dec 05, 2016 at 18:32 GMT_

----

If user A shares an in-workflow work with user B, the work will be hidden from B in search results and the show view assuming B lacks permission to advance the work from its current workflow state. I'm not sure if it's also hidden from B's dashboard. This would be worth testing/QAing. Might you have cycles for this, @vantuyls?

**Comment by mjgiarlo** [comment]
@vantuyls Can you find a few minutes to test/QA this to see if it's a problem or not?

**Comment by vantuyls** [comment]
pinging @scholarworks because i think he'd been seeing bad behavior on this a week or so ago.

**Comment by jcoyne** [comment]
@vantuyls @scholarworks what's the status of this ticket?

**Comment by scholarworks** [comment]
@jcoyne going to test/qa this today.

**Comment by scholarworks** [comment]
Here's what I did:
- New test app
- Create 3 users:
-- Admin
-- Depositor
-- generic (no roles)
-- create default admin set and assign one-step-mediated deposit workflow
-- Depositor submits and item and it lands in workflow
-- Depositor can no longer edit the item
-- Admin logs in and shares (but does not approve) the item with the no role user
-- login as no role user, the item isn't viewable or findable.
-- log back in as admin and approve
-- item is now discoverable.


@vantuyls  I believe this ticket can be closed. If I missed a use case, please let me know.

**Comment by vantuyls** [comment]
@scholarworks thanks! Looks like we're all set.
