### ISSUE TITLE
Drop "lease"?

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra-labs/hyrax#183]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jcoyne](https://github.com/jcoyne)**
_Wednesday Oct 26, 2016 at 18:02 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2825_

----

Is anyone using this feature?

**Comment by carrickr** [comment]
Avalon uses this feature pretty heavily and we'd hope to have it in the Hyrax we're basing Avalon 7 on.  Although we'd be fine with replacing your concept of lease with ours probably if you don't want your concept anymore.

**Comment by cjcolvar** [comment]
:+1: to the concept of a Lease, but we could also build the Avalon lease as a flip-floppable feature or a plugin.

**Comment by jcoyne** [comment]
@carrickr @cjcolvar It's great to hear there are important use cases out there for leases.  We just weren't sure if this was an edge-case or a mainstream need. cc @ggeisler @hannahfrost
