### ISSUE TITLE
Change Create and Edit Admin Set forms to use appropriate hint text.

### ISSUE THREAD

**Issue by laritakr** [projecthydra-labs/hyrax#201]
Both the new and the edit pages for admin sets show the simple_form default hints as descriptive text. These hints refer to works (as shown below) so are not relevant to admin set creation or editing.

More appropriate text needs to be defined, added into the appropriate hyrax yml file, and accessed 
from the relevant admin sets forms.

Screenshots:
![screen shot 2017-01-04 at 2 05 17 pm](https://cloud.githubusercontent.com/assets/17851674/21655493/4b96a058-d288-11e6-8b03-008bed9975d0.png)
![screen shot 2017-01-04 at 2 14 38 pm](https://cloud.githubusercontent.com/assets/17851674/21655499/4f2a92a6-d288-11e6-8110-1f572bb2203b.png)

**Comment by hannahfrost** [comment]
You are quire right, @laritakr.

I suggest the following hint text for the Admin Set title: 
A name to aid in identifying the Administrative Set and to distinguish it from other Administrative Sets in the repository.

And this hint text for the Admin Set Abstract/Summary:
A brief overarching description that applies to all works collected in this set. For example, "Theses and supplementary files created by the School of Earth Sciences graduate students."
