### ISSUE TITLE
Streamline Admin Set creation process

### ISSUE THREAD

**Issue by laritakr** [projecthydra-labs/hyrax#204]
### Current admin set creation

Adding a new admin set requires
1)  Take "Administrative Sets" option from Administration sidebar menu to open the List of Administrative Sets.
2) Select "Create new administrative set" button
3) Fill in title and abstract/summary sections. Click "Save". You are returned to the List of Administrative Sets.
4) Select the administrative set that you just created from the bottom of the list.
5) Click the "Edit" button from the display Administrative Set.

### Comments

After creating a new administrative set, it would be helpful to be routed directly to the Edit Administrative Set form so the remaining permissions could be modified and the workflow assigned as necessary.

The create form is identical to the first tab of the edit form. If these could be combined somehow, it might be ideal, since you would generally want to access all of the tabs as part of the add process as well as when editing.

**Comment by mjgiarlo** [comment]
Thoughts on the above, @ggeisler @jcoyne @hannahfrost?

**Comment by ggeisler** [comment]
I agree with @laritakr. On the successful creation of a new admin set, I'd display a flash message and re-present the page as if you were editing the admin set, with the additional tabs and edit title, etc.

![edit_admin_set____hyku](https://cloud.githubusercontent.com/assets/101482/21659474/16f28628-d288-11e6-8bb1-623a953a272c.png)

The main drawback I see from a UX point of view is the possibility that the user will not understand why they see the same form again, but 1) the flash message will hopefully clue them in to what's going on, and 2) presumably most users with privileges to create admin sets will do it enough for the workflow to be clear.

**Comment by mjgiarlo** [comment]
@ggeisler Building on that, I wonder if it may be worth adding another sentence highlighting the new tabs, and "welcoming" the user to explore them.

**Comment by ggeisler** [comment]
In the flash message, right @mjgiarlo? Sure, maybe something like:

> The administrative set "Test Admin Set" has been created. Use the additional tabs to define other aspects of the administrative set.

I'd suggest not getting more specific or verbose than that, because that is probably enough and getting more specific will lead to maintenance complications in the future if the purpose of the tabs change or are extended, etc.

**Comment by mjgiarlo** [comment]
@ggeisler :+1:

**Comment by laritakr** [comment]
Something to be added to the other issue to actually get the flash message working? :D

**Comment by mjgiarlo** [comment]
@laritakr Yeah, that'd be good. ;)
