### ISSUE TITLE
Lexvo languages rake task fails to add anything to the db because of a difference in namespace

### ISSUE THREAD

**Issue by geekscruff** [projecthydra-labs/hyrax#221]
### Descriptive summary

Observed in 0.0.1.alpha. When running rake hyrax:controlled_vocabularies:language no languages are added to the database. The cause is a difference in the namespace used in the lexvo data (http://www.w3.org/2008/05/skos#) and RDF::Vocab::SKOS (http://www.w3.org/2004/02/skos/core). The easiest fix would be to change the predicate in /lib/hyrax/controlled_vocabulary/importer/language.rb to match the one in lexvo (http://www.w3.org/2008/05/skos#prefLabel). I'd be happy to submit a PR with this change made.

### Expected behavior

Almost 8000 langages should be added to the qa_local_authority_entries table

### Actual behavior

No language terms are added to the database table.

### Steps to reproduce the behavior

1. Run rake hyrax:controlled_vocabularies:language
2. Once it completes check http://localhost:3000/authorities/terms/local/languages - if it's empty, you have the problem

**Comment by mjgiarlo** [comment]
Good catch, @geekscruff! I'd be happy to accept that PR. :smiley:

**Comment by geekscruff** [comment]
Excellent. I'm without my machine for a few days so will submit it by the end of the week :)

**Comment by jcoyne** [comment]
I contacted Gerard de Melo about this issue and it looks like he will update the URI at some future date:

> Thanks for pointing this out! We are in the process of setting up our
whole new infrastructure at Rutgers, so it may take a while, but we will
definitely update the SKOS URIs. I will keep you updated.
