### ISSUE TITLE
Default admin set should be created earlier

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra-labs/hyrax#237]
Default admin set should be created earlier than when the first work w/o an admin set is submitted.

**Comment by cam156** [comment]
I was looking at this, but ran into errors in my initializer. https://project-hydra.slack.com/files/cam156/F3R8JGEP5/gistfile1.txt

At this point I do not have time to debug the problems further, but from what I can tell when you initialize the it seems to think the default AdminSet is present even when it is not.

Check out branch i#237 for the code

**Comment by mjgiarlo** [comment]
@vantuyls I wonder if we should move this back to ready and unassign it?

**Comment by scholarworks** [comment]
@vantuyls @mjgiarlo I can take this over if necessary.

**Comment by mjgiarlo** [comment]
@scholarworks have at it! Thank you.

**Comment by scholarworks** [comment]
Note - This issue is important because, as is, the admin user has to create an initial item in order for the "Default Admin Set" to created. If the default admin set needs to include workflow assignments, the admin user shouldn't have to create a "dummy work" to generate the Default Admin Set.
