### ISSUE TITLE
Admin page should have a paginated list of users.

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyrax#247]
On the sidebar it's called "Manage users"

Show user name, avatar if they are an admin or not and their date of last access. This should link to the user-role edit page.

see projecthydra-labs/hyku#444 for mockup

- [ ] Add a section for user count and administrator count
- [ ] Add pagination for user page
- [ ] Add columns of Name, Username, Roles, Department, Last Access
- [ ] Add select option for updating pagination page size
- [ ] Ensure the templates for this page in Hyrax exist in Hyku as overrides
- [ ] Answer what roles we are rendering from the mockup (e.g. the Hyku `user_roles` table values, or the Hyrax `sipity_roles + sipity_workflow_roles` join)

At present, #248 is for the Filter by User Name, #249 is for Filter by Role

**Comment by mjgiarlo** [comment]
Related to #248, #249. Consider using datatables for the implementation (already being used for admin/admin_sets index view).

**Comment by mjgiarlo** [comment]
Feel free to take what's currently available at `/admin/users` (currently a submenu of Roles and Permissions), and move it into the menu structure as specified in the mockup.

**Comment by jeremyf** [comment]
Note, self assigned, but @laritakr and I are going to spend this afternoon on task breakdown.

**Comment by jeremyf** [comment]
@mjgiarlo For the Roles column in the UI, what is the source of those Roles?

**Comment by laritakr** [comment]
@ggeisler the [manage users page as designed](https://cloud.githubusercontent.com/assets/101482/20907182/edf68dd6-bb09-11e6-872b-4ec63c7601eb.png) shows content that is not exposed for entry (user name, department). Should they still be exposed on this page with blank data, or is other information desired instead?

**Comment by ggeisler** [comment]
@laritakr I don't think we should show fields that we know will be blank for all users, so I'd leave those out for now. I'll make another ticket that proposes to add other fields I think we'd want to enable users to add. Sorry for the confusion.

**Comment by laritakr** [comment]
closed via https://github.com/projecthydra-labs/hyrax/pull/547
