### ISSUE TITLE
Manage users page should have a filter for only admins

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyrax#249]
Making it easy to find the admin users amongst all the non-admins. see projecthydra-labs/hyku#444 for mockup

**Comment by mjgiarlo** [comment]
Related to #248, #247. Consider using datatables for the implementation (already being used for admin/admin_sets index view).

**Comment by laritakr** [comment]
The use of datatables in the admin users page takes care of this requirement.
