### ISSUE TITLE
Back button gets broken

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyrax#254]
If you go to https://nacho.demo.hydrainabox.org/admin/admin_sets/9p2909328/edit

Then click the workflow tab (https://nacho.demo.hydrainabox.org/admin/admin_sets/9p2909328/edit#workflow)
and then click the notifications (https://nacho.demo.hydrainabox.org/notifications?locale=en), then click the back button, it doesn't go back.

**Comment by atz** [comment]
I guess the demo site has been cleaned out?  I get `The page you were looking for doesn't exist.`

**Comment by atz** [comment]
Maybe I'm using the wrong creds/acct.  What user should I be using?

**Comment by jcoyne** [comment]
Those were just example urls. You can reproduce in your local install

**Comment by andjsmit** [comment]
Looks like this is a know problem with Bootstrap tabs. Possible fix : https://gist.github.com/josheinstein/5586469 or http://www.redotheweb.com/2012/05/17/enable-back-button-handling-with-twitter-bootstrap-tabs-plugin.html . Will give it a try.

**Comment by andjsmit** [comment]
Fixed by @jcoyne : https://github.com/projecthydra-labs/hyrax/pull/732
