### ISSUE TITLE
Zero-work collections in "Recent collection activity" widget

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra-labs/hyrax#255]
The "Recent collection activity" widget in the Admin Dashboard displays nothing in the "Works" column when collections (admin sets) have 0 works. Instead, the widget should display "0".

**Comment by andjsmit** [comment]
![screen shot 2017-01-13 at 5 19 16 pm](https://cloud.githubusercontent.com/assets/333335/21947711/87cf96e6-d9b4-11e6-98ad-06d49ea3b538.png)
