### ISSUE TITLE
Sipity::WorkflowState entities has_many references the wrong class

### ISSUE THREAD

**Issue by cam156** [projecthydra-labs/hyrax#259]
### Descriptive summary

In Master when I access the entities in a workflow an error is thrown becuase the entities are 'Sipity::Entity' not 'Sipity::Workflow'

https://github.com/projecthydra-labs/hyrax/blob/master/app/models/sipity/workflow_state.rb#L19

**Comment by mjgiarlo** [comment]
Fixed by #261, closing.
