### ISSUE TITLE
Permission template should belong to admin set

### ISSUE THREAD

**Issue by laritakr** [projecthydra-labs/hyrax#265]
### Descriptive summary

According to slack conversations, permission template must always belong to an admin set. 

### Expected behavior

Add a model validation for presence of admin set id on the permission template (also consider adding a database constraint for that field).

### Actual behavior

We can create and persist permission templates with a nil admin set id. 

This is where we found the problem:

```ruby
      def permission_template
        PermissionTemplate.find_or_initialize_by(admin_set_id: @admin_set.id)
      end
```
https://github.com/projecthydra-labs/hyrax/blob/52e6e6263df7cde2c947bf626ad4f58423c14749/app/controllers/hyrax/admin/admin_sets_controller.rb#L104

**Comment by jcoyne** [comment]
I think this is now fixed https://github.com/projecthydra-labs/hyrax/pull/459 

related to #256
