### ISSUE TITLE
Show works page column alignment issue

### ISSUE THREAD

**Issue by laritakr** [projecthydra-labs/hyrax#277]
The metadata columns on the show works page do not line up correctly.

The code which generates the linkable text inserts the links as list items into the table row, so the links do not align with the titles or other (unlinked) column text.

```
<ul class="tabular">
<li class="xxx"><a href="/xxx">label</a></li></ul>
```

![screen shot 2017-01-17 at 3 20 24 pm](https://cloud.githubusercontent.com/assets/17851674/22039607/f44f45fc-dccd-11e6-842a-1f975509a46f.png)

**Comment by atz** [comment]
So is the fix to replace the table-view with different structure, preferably something bootstrappy?

**Comment by mjgiarlo** [comment]
Thoughts on how best to display the metadata :arrow_up:, @ggeisler?

**Comment by ggeisler** [comment]
Well, to fix the specific issue  I believe @laritakr is reporting, we can simply remove the left padding on the ```ul``` used to show the linked text:

``` css
ul.tabular {
  padding-left: 0;
}
```
That will line things up fine:

![test_item](https://cloud.githubusercontent.com/assets/101482/22130441/3a3cd3b2-de69-11e6-95fd-4caac80ea2d7.png)

(I'm not familiar enough with the project CSS to know, but we might want to make that scope more specific if the tabular class is used on `ul`s elsewhere.)

There might be a larger question here about the design of the Works show page itself, but that is more of design needed thing and I don't think that what's @laritakr was reporting, and it's probably lower-priority than other design needed things.

**Comment by mjgiarlo** [comment]
Thanks, @ggeisler!
