### ISSUE TITLE
Cut the 1.0.0 RC and create a 1.0-stable branch

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra-labs/hyrax#278]
This will serve as a migration target for folks coming from Sufia and CurationConcerns. See here for more information: https://wiki.duraspace.org/pages/viewpage.action?pageId=78161232#Sufia/CurationConcernsConsolidationPlan-I'mreadytomigratemyapplicationfromSufiaorCurationConcernstoHyrax.WhatversionofHyraxshouldItarget?

- [ ] Cut `1.0.0.rc1` release
- [ ] Create `1.0-stable` branch

**Comment by mjgiarlo** [comment]
Cc: @jcoyne @hackmastera

**Comment by atz** [comment]
I thought Trey was asking for a release **candidate**.

**Comment by mjgiarlo** [comment]
@atz I believe he was suggesting a friendly amendment to to what I proposed in this issue.

Now that we've got the `0.1-stable` branch cut, and thus some separation between ongoing feature development and a migration path, I'm not sure what we call the release matters too much at this point.

**Comment by atz** [comment]
@mjgiarlo: Eh?  You were just agreeing w/ Trey when he said `I wouldn’t leave the release candidate process until a CC app conversion to hyrax has happened.`  I interpret that to mean "I would not cut a **non-RC** 1.x release until..."

I don't see what the "stable" branch (or any other) is worth in this conversation ostensibly about SemVer release management.

**Comment by mjgiarlo** [comment]
@atz I believe Trey was agreeing with me about being
> hesitant to pull the trigger on 1.0 before someone with a CC hat on takes a really close look at things

It seems we're in agreement that we shouldn't cut any non-RC 1.x releases any time soon. Where there may be some room for discussion is around how many 0.x releases come out before we say we're in 1.0 RC land.

In the meantime, I don't see a problem with cutting one or more 0.1.x releases if they would help folks start assessing the upgrade path from Sufia/CC. For now, I think we're in a good spot having the branch we have, since the reason for this ticket was less related to SemVer proper and more about coming up with a way to provide separation between work flowing into `master` and Hyrax's current "proximity" to Sufia/CC `master`.

**Comment by mjgiarlo** [comment]
Blocked by Sufia 7.3.0 release.

Release 7.3.0 first; merge changes into Hyrax `0.1-stable` and `master`; then take on this ticket.

**Comment by mjgiarlo** [comment]
Sufia 7.3.0 is now released.

**Comment by jcoyne** [comment]
I released 1.0.0.rc1 and created the 1-0-stable branch today.
