### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by atz** [projecthydra-labs/hyrax#279]
- Refers to the Dec. 2016 sprint in the future tense.  Needs a summary statement about development.
- Give structure to the sprawling feature list.  40 or 50 bullet points is not readable or persuasive.  Break into sections like "Data Modeling", "Integrations", "Discovery", "UI/UX/Design", etc.
- The first sentence after the "**What is Hyrax?**" title should literally answer the question.  "Hyrax is...", not "Hyrax uses...".  References to Sufia and CurationConcerns there should be links.

**Comment by mjgiarlo** [comment]
Thanks for writing these up!

Re: the second bullet point, I just culled that list in the Sufia README today, so the next merge from Sufia will take care of that.

**Comment by mjgiarlo** [comment]
These have all been done now.
