### ISSUE TITLE
Allow for work types to be in a namespace

### ISSUE THREAD

**Issue by cam156** [projecthydra-labs/hyrax#291]
For a work type like a book, can we allow for namespaces so that different kinds of books can be created in apps.  At this point, I believe, the work must live in `app/models/concerns/book`. It would be nice if they could live in `app/models/my_plugin/book` or in a gem in `[path_to_my_plugin]/app/models/my_plugin/book.rb`

**Comment by mjgiarlo** [comment]
Thoughts on the above, @projecthydra-labs/hyrax-code-reviewers?

**Comment by jcoyne** [comment]
@cam156 you could do this, but this would require a data migration as ActiveFedora stores the class name as an assertion on the fedora object.

**Comment by cam156** [comment]
@jcoyne I should have said optional namespace.
I was thinking the the command would work as normal in this instance
```
rails g hyrax:work book
```

But in this instance it would create the directory.
```
rails g hyrax:work my_plugin::book
```

By playing with the command it seems to just create the book model named incorrectly currently.

**Comment by jcoyne** [comment]
I suggest we write the ticket in this way:
> As a developer
when I run `$ rails g hyrax:work my_plugin/book` I should see 
the model, controller, actor, form and locales generated with the my_plugin namespace and they should be in a my_plugin subdirectory.
additionally the line `  config.register_curation_concern ...` generated in `config/initializers/hyrax.rb`  should define a namespace.
The generated routes should have the namespace in their path.


The current behavior is that it adds the namespace to the generated files, but puts them in the wrong directory.  The routes are not namespaced.

**Comment by atz** [comment]
Note: this needs to avoid conflicting with the optional `field:type` arguments that are part of the signature for that generator:

    rails generate hyrax:work NAME [field:type field:type]
