### ISSUE TITLE
hyrax:work generator is not reversible

### ISSUE THREAD

**Issue by atz** [projecthydra-labs/hyrax#301]
Specifically the `register_work` method as described in #295.  

We ask the method to do a mildly complicated task (for a generator), since it has to preserve the order of inserted lines.  Note that logical variation in the content to be inserted (the additional comment line) is problematic (it would never get deleted, since `destroy` would only be run when lines are already added).  Probably can be removed.

**Comment by mjgiarlo** [comment]
@atz Is there a use case for making the generator reversible outside the context of test idempotence? That will help me prioritize and label this issue.

**Comment by atz** [comment]
Definitely.  Like migrations, reversibility is a core feature of the generator model... in theory anyway.  In practice, it is useful anytime a user would want to remove a generated class, like after a typo.  Or after remediating legacy data from a deprecated work type to a newer one.

**Comment by atz** [comment]
I wouldn't say it a high priority though.

**Comment by mjgiarlo** [comment]
Thanks, @atz. I'm labeling this as technical debt, since we apparently never bothered to implement the `:revoke` behavior despite calling it in our specs. Here's a technique for building in revocation: http://factore.ca/blog/126-reversible-rails-generators
