### ISSUE TITLE
i18n strings contain HTML in non-html keys

### ISSUE THREAD

**Issue by atz** [projecthydra-labs/hyrax#327]
See #315 

These i18n values contain HTML but are not in keys named `*_html`.  That means there HTML will be displayed escaped.

```
config/locales/hyrax.en.yml:        based_near: "A place name related to the collection, such as its site of publication, or the city, state, or country the collection contents are about. Calls upon the <a href='http://www.geonames.org'>GeoNames web service</a>."
config/locales/hyrax.en.yml:        based_near: "A place name related to the work, such as its site of publication, or the city, state, or country the work contents are about. Calls upon the <a href='http://www.geonames.org'>GeoNames web service</a>."
config/locales/hyrax.es.yml:        based_near: "Nombre de un lugar relacionado con la colección, tal como el sitio de publicación, o ciudad, estado, o país, que esté relacionado con los contenidos de la colección. Llamados a través del servicio de <a href='http://www.geonames.org'>GeoNames</a>."
config/locales/hyrax.es.yml:        based_near: "Nombre de un lugar relacionado con el trabajo, tal como el sitio de publicación, o ciudad, estado, o país, que esté relacionado con los contenidos de el trabajo. Llamados a través del servicio de <a href='http://www.geonames.org'>GeoNames</a>."
```

Solution is to rename the key in files and wherever they are used.

**Comment by jcoyne** [comment]
These i18n are for simple_form and thus do not follow the `_html` convention. All simple_form hints are html safe.  See https://github.com/plataformatec/simple_form/blob/c3a307cb9501208e053f771738e34a3d93d33858/lib/simple_form/components/hints.rb#L13

**Comment by atz** [comment]
Then we need a naming convention or at least some comments so that one can tell *from the translation file* what the simple_form components are.  In particular so they don't get reused in the wrong context.

**Comment by jcoyne** [comment]
@atz those keys are already in the simple form namespace: `simple_form.labels.collection.based_near` and ``simple_form.labels.defaults.based_near`

**Comment by atz** [comment]
Ah, word.  That works then.
