### ISSUE TITLE
Top of page wraps oddly, makes usability bad

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyrax#362]
<img width="868" alt="screen shot 2017-02-06 at 11 08 11 am" src="https://cloud.githubusercontent.com/assets/92044/22662095/a735c748-ec5c-11e6-82c6-027c09049862.png">

**Comment by mjgiarlo** [comment]
Thoughts on the above re: how it should wrap, @projecthydra-labs/hyrax-ui-ux-advisors @ggeisler ?

**Comment by newmanld** [comment]
If Hyrax is behaving like Sufia 7.3, it looks like the wrapping occurs in a window between the hamburger menu and a non-wrapped state.  Would it be acceptable to go directly to the hamburger menu and never wrap?

**Comment by mtribone** [comment]
In ScholarSphere, I put them in different rows so that they can shrink and expand.

![screen shot 2017-02-06 at 2 49 18 pm](https://cloud.githubusercontent.com/assets/4163828/22663714/acd1778c-ec7b-11e6-9a74-502805713db3.png)

**Comment by newmanld** [comment]
If we can avoid an additional row, I would, as I like having a header that doesn’t become too tall.   (Local variation may/will differ.)

**Comment by mccallum** [comment]
Is Administration the mode you're in and not clickable? The gear icon on Administration there is used for "Settings" traditionally. I'd find a way to get some space there if it's just a label for the mode you're in. And then notifications could use just the bell notificaiton convention - ala Github, Google, Yahoo, etc.

**Comment by jcoyne** [comment]
@mtribone Your design doesn't have the language switcher incorporated yet. I feel it too would be a little crowded after adding that. 

@mccallum some accessibility experts have mentioned in the past that they prefer all icons to also have visible text.

**Comment by mccallum** [comment]
@jcoyne True that. If the bell was the choice, it would have to be as ARIA-fied as Github, Google and Yahoo are.

**Comment by mtribone** [comment]
@jcoyne Could the language prefs be in the dropdown under the person's name?

**Comment by ggeisler** [comment]
A couple of months ago I created https://github.com/projecthydra-labs/hyku/issues/502 as a placeholder for removing the links from the top-bar completely. This is much different from Sufia so I understand that not everyone will like the idea (and I'm not suggesting it for Sufia, just Hyku), but I believe it is compatible the addition of the administrative sidebar and the overall design plan for Hyku.

When the user wants to do admin-like stuff (including a non-admin user who wants to add a work or a collection), they use a link under the name pulldown to get to the admin side of things, where links to everything currently exposed in the top bar are readily available. Basically the way Spotlight works. This keeps the visual design of the site uncluttered and avoids the wrapping issue.

 I will do a full mockup in https://github.com/projecthydra-labs/hyku/issues/502 when time and priorities allow.

@jcoyne: I believe @hannahfrost was planning to go over this with you this week.

**Comment by hannahfrost** [comment]
@ggeisler Yeah, @jcoyne and I discussed this morning. I'm going to start creating Hyrax tickets along the lines we discussed. Thanks.

**Comment by ggeisler** [comment]
Given #482 is complete and we've removed a bunch of links from the top bar, I think this ticket can be closed? Current version of the top bar supports about 43 characters before causing a wrapping issue, at the most minimal width where we still show all the top bar elements:

![hyrax](https://cloud.githubusercontent.com/assets/101482/25153638/1bc91c46-2442-11e7-8638-ac36a2ecd71f.png)

Probably sufficient unless we hear from institutions that need more space than this for their institution name?
