### ISSUE TITLE
Some way to disable share pane without overriding _guts4form.html.erb

### ISSUE THREAD

**Issue by tpendragon** [projecthydra-labs/hyrax#370]
Plum's user permissions are all handled via roles assigned from the admin panel and CanCan, users shouldn't be able to control access permissions to groups, so we needed to disable the share pane. Only way to do that was to override guts4form, which seems problematic.

**Comment by jcoyne** [comment]
In addition to enabling part of the `_guts4form.html.erb` this setting should also impact whether these parameters are permitted.  This would likely be a change to https://github.com/projecthydra-labs/hyrax/blob/master/app/forms/hyrax/forms/work_form.rb#L122

**Comment by mjgiarlo** [comment]
This is high priority.

**Comment by jcoyne** [comment]
Fixed by https://github.com/projecthydra-labs/hyrax/commit/2628ec23e077050c87022ee8f4cbf222f0a6f4f4

**Comment by mjgiarlo** [comment]
@tpendragon The above commit adds an `allows_access_grant` attribute to the workflow json. When set to `false`, the sharing form is disabled. Does that sound workable?

**Comment by tpendragon** [comment]
I think so.
