### ISSUE TITLE
Support YAML as configuration for FlipFlop

### ISSUE THREAD

**Issue by tpendragon** [projecthydra-labs/hyrax#372]
For CC users who want configuration as part of the codebase (Plum users included.)

**Comment by jcoyne** [comment]
Does the existing default strategy satisfy this requirement?

**Comment by tpendragon** [comment]
I don't think so, unless there's a nice way to change what the defaults are?

**Comment by mjgiarlo** [comment]
@jcoyne @tpendragon What if we add the config gem to Hyrax like we did in Hyku:

https://github.com/projecthydra-labs/hyku/commit/f1ebe145be6824a2bd6da76231a3eaa74e73e34f

And then change Flipflop's config file:

https://github.com/projecthydra-labs/hyrax/blob/master/config/features.rb

To ask the config gem (which can be expressed as YAML) what the default values for these features are?

**Comment by mjgiarlo** [comment]
We could even add a flag to the Hyrax install generator that picks either the "Sufia" or "CurationConcerns" flavor YAML configs or some such.

**Comment by tpendragon** [comment]
@mjgiarlo Sorry for the delay, I don't get notifications separated out for hyrax issues yet (the generic github folder of my email may as well be trash at this point). Yeah, that would be fine.
