### ISSUE TITLE
JS doesn't support jQuery 3.

### ISSUE THREAD

**Issue by tpendragon** [projecthydra-labs/hyrax#374]
Need to replace all our `.size()` calls with `.length` - after that it all seems to work.

**Comment by jcoyne** [comment]
Can you be more specific? I'm using jquery-rails 4.2.2, which I has jquery 3.1.1. and I believe all is working.

**Comment by tpendragon** [comment]
```
jQuery.fn.jquery # => "3.1.1"
```

I think you only get jQuery 3 if you require jquery3 in your application.js. Anyways, what would happen is things like the edit form would say size() not a function, because it was deprecated in jQuery 1.8 and removed in 3.0 (https://api.jquery.com/size/)

**Comment by jcoyne** [comment]
Sounds good. It looks as though we had something older:
```
jQuery.fn.jquery
"1.12.4"
```
