### ISSUE TITLE
Wrong gem version in template.rb

### ISSUE THREAD

**Issue by little9** [projecthydra-labs/hyrax#378]
### Descriptive summary

The README instructions use template.rb, which has the wrong gem version. This causes this command to fail. 

### Expected behavior

The rails new command succeeding. 

### Actual behavior

It fails when trying to download the hyrax gem. 

### Steps to reproduce the behavior

Run this: 

```bash 
rails new my_app -m https://raw.githubusercontent.com/projecthydra-labs/hyrax/master/template.rb
```

**Comment by mjgiarlo** [comment]
Closed by #379. Thanks, @little9!
