### ISSUE TITLE
Upgrade guide from Sufia 7.3

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyrax#4]
## Changes

* Move all `app/views/curation_concerns` views to `app/views/hyrax`
* Move `app/controllers/curation_concerns` to `app/controllers/hyrax`
* Move `app/actors/curation_concerns` to `app/actors/hyrax`
* Move `app/forms/curation_concerns` to `app/forms/hyrax`
* Move `app/presenters/curation_concerns` to `app/presenters/hyrax`
* change the namespace of all controllers from `CurationConcerns` to `Hyrax`
* Remove `include CurationConcerns::CurationConcernController`. Ensure that `    self.curation_concern_type = GenericWork` comes after `include Hyrax::WorksControllerBehavior`
* Remove `include Sufia::Catalog` from `app/controllers/catalog_controller.rb`
* Set `config.search_builder_class = Hyrax::CatalogSearchBuilder` in `app/controllers/catalog_controller.rb`
* Remove `Hydra::BatchEdit.add_routes(self)` from the routes.
* Remove `mount CurationConcerns::Engine, at: '/'` from the routes
* Remove `include CurationConcerns::MainAppHelpers` from `app/models/sufia_helper.rb`
* Remove `include CurationConcerns::ApplicationControllerBehavior` from `app/controllers/application_controller.rb`
* Remove the files `app/assets/javascripts/batch_edit.js` and `app/assets/stylesheets/batch_edit.scss`
* Create a migration to migrate `sufia_features` to `hyrax_features`
* Make sure any tweaks made in the Sufia or CC initializer move over into the Hyrax initializer
* Remove `app/controllers/curation_concerns/admin_controller.rb` since the `AdminControllerBehavior` no longer exists

**Comment by mjgiarlo** [comment]
Should all the `sufia` here be `hyrax`, or are there vestiges of Sufia in hyrax yet?

**Comment by jcoyne** [comment]
Yeah `s/sufia/hyrax/g`

**Comment by mjgiarlo** [comment]
Also:

* Make sure any tweaks made in the Sufia or CC initializer move over into the Hyrax initializer.

**Comment by mjgiarlo** [comment]
This has been completed and tested by 3-4 institutions now. Closing. https://github.com/projecthydra-labs/hyrax/releases/tag/v1.0.0.rc2****
