### ISSUE TITLE
Default value for institution-level visibility label should be "Institution"

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyrax#404]
Hyrax supports the ability to configure the name of the institution, so that the name can be displayed as a customization across the repository in labels, etc., using variables. The default value currently appears to be "Hydra in a Box". 

It should be changed to "Institution"

Acceptance criteria:

- [ ]  I have not configured the name of my institution, and when I view the Deposit Agreement, I see the blue label for institution-level visibility reads "Institution".
- [ ] I have configured the name of my repository as "Foo", and when I view the Deposit Agreement, I see the blue label for institution-level visibility reads "Foo".

**Comment by atz** [comment]
That appears to already be true for Hyrax:
https://github.com/projecthydra-labs/hyrax/blob/master/config/locales/hyrax.en.yml#L419

The problem for Hyku is where it overrides these values.

**Comment by atz** [comment]
See #403

**Comment by hannahfrost** [comment]
@atz Are you saying that the "Hydra in a Box" I'm seeing on demo.hydrainabox.org was entered somewhere? Not by me in my tenants, it wasn't.

**Comment by mjgiarlo** [comment]
This value is currently configured in code. I assume we want to override this with the value entered per-tenant.

**Comment by atz** [comment]
@mjgiarlo I see this getting fixed in Hyku, not Hyrax.  Am I missing something?

**Comment by mjgiarlo** [comment]
@atz This may require more analysis. As a test, I'd be interested in knowing whether tweaking the institution name in Hyrax effectively changes the "Institution" label everywhere it appears in the UI. If we confirm this is :100: :ok: in Hyrax, yes, it's a Hyku ticket. As it stands, this could require work in both codebases.

**Comment by jcoyne** [comment]
Fixed by #456
