### ISSUE TITLE
CanCan should be used to check if users can append to a collection.

### ISSUE THREAD

**Issue by tpendragon** [projecthydra-labs/hyrax#408]
https://github.com/projecthydra-labs/hyrax/blob/master/app/actors/hyrax/actors/add_as_member_of_collections_actor.rb#L20

That should be something like:

```ruby
          other_collections = curation_concern.member_of_collections.select { |coll| !ability.can?(:edit, coll) }
```

Related to #407

**Comment by jcoyne** [comment]
:+1:
