### ISSUE TITLE
Should form hints have defaults

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyrax#43]
https://github.com/projecthydra-labs/hyrax/blob/master/config/locales/hyrax.en.yml#L628

The labels currently have defaults already.

This allows us to generate more work types and have translations already complete.

See https://github.com/projecthydra-labs/hyku/pull/542

**Comment by mjgiarlo** [comment]
@jcoyne first stab at this: https://github.com/projecthydra-labs/hyrax/pull/45

**Comment by mjgiarlo** [comment]
Fixed by #45.
