### ISSUE TITLE
Copy over I18n labels for default facets in CC

### ISSUE THREAD

**Issue by tpendragon** [projecthydra-labs/hyrax#432]
In CC this is everything under `blacklight.search.fields.facet` and `.index`.

**Comment by jcoyne** [comment]
I'm wondering if that stuff actually belongs in the local app, not the engine.  It seems that's a companion to the CatalogController (generated into the engine) and would need to be changed as any facet is added or removed.

**Comment by tpendragon** [comment]
@jcoyne Maybe! I made the issue because it was something I had to do (which is kind of hard to figure out, our I18n file is biiiigg) during migration.

**Comment by jcoyne** [comment]
@tpendragon there's no question we have an issue. I just want to explore alternative solutions to the problem.
