### ISSUE TITLE
Add left sidebar to Works page where logged-in user manages their work(s)

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyrax#443]
Per https://github.com/projecthydra-labs/hyrax/issues/441

![works](https://cloud.githubusercontent.com/assets/1801076/23085378/49751820-f51c-11e6-88d5-751a999a2d7c.png)

**Comment by jcoyne** [comment]
@ggeisler as this user is not an admin, should the breadcrumbs say "Administration" here?

**Comment by hannahfrost** [comment]
@jcoyne I discussed a similar question with @ggeisler recently. The answer is yes: "Administration" in this context is about function, not meant to be used in the UI only for explicitly admin (or manager) roles. Logged-in users (eg Depositors) who are not Repository Administrators have tasks that are administrative and content management-y in nature, and this is the best overarching term we could come up with for the navigation. Note that #441 describes how "Administration" is the term used in the upper right menu for a user to navigate to this page. Do you have suggestions for a different term to use for this section of the site?
