### ISSUE TITLE
Saving a change to admin set workflow selection results in wrong flash message and displayed tab

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyrax#463]
When I click "save" on the Workflow tab of the Edit Admin Set screen, the page loads showing the Release and Visibility tab with this flash message appearing: "The administrative set's visibilty settings have been updated."

After clicking "save", I would expect to remain on the Workflow tab with a flash message that says, "The administrative set's workflow settings have been updated."

**Comment by laritakr** [comment]
Resolved by https://github.com/projecthydra-labs/hyrax/pull/490
