### ISSUE TITLE
Default admin set, does not have an active workflow.

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyrax#470]
When I run the Actor (without having previously created the default AdminSet) i get this error:

```
     ActiveRecord::RecordNotFound:
       Couldn't find Sipity::Workflow with [WHERE "sipity_workflows"."active" = $1 AND "sipity_workflows"."permission_template_id" IN (SELECT "permission_templates"."id" FROM "permission_templates" WHERE "permission_templates"."admin_set_id" = 'admin_set/default')]
     # /Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.1/lib/active_record/relation/finder_methods.rb:550:in `find_nth!'
     # /Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.1/lib/active_record/relation/finder_methods.rb:129:in `first!'
     # /Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/hyrax-22714f043af3/app/models/sipity/workflow.rb:34:in `find_active_workflow_for'
     # /Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/hyrax-22714f043af3/app/models/concerns/hyrax/in_admin_set.rb:10:in `active_workflow'
     # /Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/hyrax-22714f043af3/app/services/hyrax/workflow/workflow_factory.rb:41:in `active_workflow'
     # /Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/hyrax-22714f043af3/app/services/hyrax/workflow/workflow_factory.rb:32:in `create'
     # /Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/hyrax-22714f043af3/app/services/hyrax/workflow/workflow_factory.rb:12:in `create'
     # /Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/hyrax-22714f043af3/app/actors/hyrax/actors/initialize_workflow_actor.rb:15:in `create_workflow'
     # /Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/hyrax-22714f043af3/app/actors/hyrax/actors/initialize_workflow_actor.rb:8:in `create'
```

@jeremyf should DefaultAdminSetActor create the PermissionTemplate with an active workflow? If not, we should refactor DefaultAdminSetActor to raise an error if no admin sets exist.

- [x] Create configurable default workflow name
- [x] Consolidate logic for creating workflows [defuault](https://github.com/projecthydra-labs/hyrax/blob/master/app/actors/hyrax/default_admin_set_actor.rb#L35) [AdminSetCreateService](https://github.com/projecthydra-labs/hyrax/blob/master/app/services/hyrax/admin_set_create_service.rb#L1)

**Comment by jcoyne** [comment]
This is now an issue, because the WorkflowFactory used to load the workflows automatically in this commit: https://github.com/projecthydra-labs/hyrax/pull/459/files#diff-3e949475c3590985b8ae20f49560f323L48

**Comment by jeremyf** [comment]
Two paths that I see straight away:

* Ensure that we have a magic `default` workflow that can be activated when we create the admin set
* Raise an error if no admin set exists (instead of creating them outright)

However, I believe there is work being done to ensure that we have a default admin set as part of the initialization. Which means we likely need a default workflow as part of the initialization. Perhaps a configuration option?

**Comment by jcoyne** [comment]
Will https://github.com/projecthydra-labs/hyrax/pull/433 resolve this?

**Comment by jeremyf** [comment]
@jcoyne I don't think so - the workflow importer does not make a decision on activation. We could add an attribute to the workflow config saying "active"; I think the better mechanism is to have a configuration option that says "this is the default active workflow name for the admin_set".
