### ISSUE TITLE
Creating a new AdminSet (or editing one) results in an error

### ISSUE THREAD

**Issue by tdonohue** [projecthydra-labs/hyrax#478]
### Descriptive summary

On latest `master` (HEAD: https://github.com/projecthydra-labs/hyrax/commit/d3b98b19cf96e6b54a761f2e1005df318af43504), creating a new AdminSet results in this error:

`undefined method 'id' for nil:NilClass`  at https://github.com/projecthydra-labs/hyrax/blob/master/app/forms/hyrax/forms/permission_template_form.rb#L24

This seems related to #470, but also seems to affect newly created AdminSets (non-default).

After the error occurs, I can go back and see the AdminSet was successfully created. However, I'm not able to edit that AdminSet (results in the same error), unless I comment out the `||  active_workflow.id` portion of that line.

### Steps to reproduce the behavior

1. Update to latest master
1. Create a new AdminSet (or attempt to edit one that doesn't have an active workflow)

**Comment by tdonohue** [comment]
Strangely, we have a feature spec which seems to be validating AdminSet creation/editing:
https://github.com/projecthydra-labs/hyrax/blob/master/spec/features/admin_admin_set_spec.rb#L26

However, I'm not certain why that spec succeeds while my (manual) tests result in an error.

**Comment by jcoyne** [comment]
That test is for an edit. Perhaps the create path is different?

**Comment by tdonohue** [comment]
Quick update, I unfortunately don't have a full PR. But, the quick fix is to change `active_workflow.id` to ` active_workflow.try(:id)` on this line: https://github.com/projecthydra-labs/hyrax/blob/master/app/forms/hyrax/forms/permission_template_form.rb#L24

I'm still working on getting an feature spec to validate this change (hence no PR).

**Comment by tdonohue** [comment]
@jeremyf : I've noticed you are working on resolving #470 (in #486) , which is loosely related to this same issue (although this one is around creating _new_ adminsets).  Have you done any work to fix this issue? If not, I can claim this.  The quick fix is above (see my previous comment), but we are missing a feature spec to validate this.

**Comment by jeremyf** [comment]
This should be solved when #486 is merged.

**Comment by tdonohue** [comment]
Retested, this is fixed by #486 (which was merged). Closing.
