### ISSUE TITLE
Are flash messages in the right spot?

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyrax#491]
<img width="1335" alt="screen shot 2017-02-27 at 8 56 31 am" src="https://cloud.githubusercontent.com/assets/92044/23365980/badfa240-fcca-11e6-9edb-849c94d09117.png">

@ggeisler is this the correct place for a flash message?

**Comment by ggeisler** [comment]
For that message, yes, because it is in response to a global action.

If instead the flash message is conveying information about an action that was completed in a form in the main content (light gray) area, then I think it would be more appropriate to put it below the breadcrumb.

**Comment by jcoyne** [comment]
@ggeisler at this time we don't have a way of differentiating those types of messages.

**Comment by ggeisler** [comment]
Okay, leave it where you have it and maybe in the future when the app is more polished we can decide if it's okay there or needs to move.

**Comment by hannahfrost** [comment]
Sounds reasonable to me, @ggeisler. 

@jcoyne Is this still "design needed"?

**Comment by hannahfrost** [comment]
@jcoyne Can we close this now?
