### ISSUE TITLE
How should we use the installation template?

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra-labs/hyrax#492]
How should Hyrax use the [installation template](https://github.com/projecthydra-labs/hyrax/blob/master/template.rb)? @jcoyne and I went back and forth on this for Sufia 7.x, with the two options being:

1. README always points at the template in the master branch, and the template is updated with each release to point at the latest release. This means that the README will always install the latest stable release of Hyrax.
1. README always points at the template corresponding to the current release. So if you're reading the README for Hyrax 1.2.0, you get Hyrax 1.2.0 installed. If you're reading the README for 0.1.0, you get 0.1.0 installed. If you're reading the README in master, you get the latest stable release of Hyrax. (In order to do this, we'd need to update the README and the template with each release, as ticketed here: projecthydra/sufia#2784)

I'd welcome @projecthydra-labs/hyrax-code-reviewers thoughts on this.

# Past discussions

* https://github.com/projecthydra/sufia/pull/2783#pullrequestreview-3965724
* https://github.com/projecthydra/sufia/issues/3075
* https://github.com/projecthydra/sufia/issues/2784

**Comment by tpendragon** [comment]
I vote for #2.

**Comment by mcritchlow** [comment]
+1 on #2. Seems like a reasonable step in the release workflow, and I (personally) like that it's more explicit.

**Comment by jcoyne** [comment]
I'm for #1. I don't believe there is a use case where someone wants to use the template, knows the version they want to install, and it's not the most recent version.

**Comment by jcoyne** [comment]
I'm actually going to propose a 1.1 option. The template should just say `gem 'hyrax'`. Bundler will grab the most up to date version.

**Comment by mcritchlow** [comment]
@jcoyne While we're adding other options ;), would a 1.2 option be possible? Essentially: `require 'lib/hyrax/version'` in the template and interpolating the gem version?

**Comment by mjgiarlo** [comment]
@jcoyne It seems like you're (perhaps reasonably) making a YAGNI argument. But, given the :+1:s above (and my own :+1:), and the very low cost of going with option number 2, is there another reason not to do this?

**Comment by jcoyne** [comment]
Yes, YAGNI. It's just one more little thing to do.  It's fine to outvote me, but now you know my mind

.

**Comment by mcritchlow** [comment]
As one of the 👍 'ers, I should say I'm also happy to help with this process also. Wouldn't be very fair to say "yes, someone **else** should do this extra thing" :)

**Comment by no-reply** [comment]
I'm currently trying to start a new project based on `1.0.0.rc1`. The template included in that tag points to `2.0.0.alpha` in conflict with the `Gemfile` version. The error output I get is:

```
Fetching dependency metadata from https://rubygems.org/..
Could not find gem 'hyrax (= 1.0.0.alpha)' in https://github.com/projecthydra-labs/hyrax.git (at master@a8ee769).
Source contains 'hyrax' at: 2.0.0.alpha ruby
    generate    hyrax:install
The git source https://github.com/projecthydra-labs/hyrax.git is not yet checked out. Please run `bundle install` before trying to start your application
       rails    db:migrate
The git source https://github.com/projecthydra-labs/hyrax.git is not yet checked out. Please run `bundle install` before trying to start your application
       rails    hyrax:workflow:load
The git source https://github.com/projecthydra-labs/hyrax.git is not yet checked out. Please run `bundle install` before trying to start your application
         run  bundle install
Fetching https://github.com/projecthydra-labs/hyrax.git
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/.......
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Could not find gem 'hyrax (= 1.0.0.alpha)' in https://github.com/projecthydra-labs/hyrax.git (at master@a8ee769).
Source contains 'hyrax' at: 2.0.0.alpha ruby
         run  bundle exec spring binstub --all
The git source https://github.com/projecthydra-labs/hyrax.git is not yet checked out. Please run `bundle install` before trying to start your application
```

The `README.md` also simply points to the current `master`, which successfully installs Hyrax `2.0.0.alpha`, so users need to know to update that template to the tagged ref manually in order to even reach the above error state.

**Comment by jcoyne** [comment]
@no-reply if you install the template on master (which is 2.0.0.alpha) it will install 1.0.0.rc1 (the most recent release.  This is how I believe you should do it.

**Comment by mjgiarlo** [comment]
All, given the discussion and voting above, I'm going to say we're going with option 2 -- I don't see a downside, other than a very small cost (a few extra seconds) at the time we cut a release, which isn't that often.

I hope that will prevent the Tom Johnsons of the future from getting bitten by the template. I will update our release management documentation so that it includes the necessary steps.

Thanks for the discussion, y'all.
