### ISSUE TITLE
Add user to group fails

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyrax#506]
<img width="1031" alt="screen shot 2017-02-27 at 5 24 35 pm" src="https://cloud.githubusercontent.com/assets/92044/23384668/a516e2c4-fd11-11e6-92a8-db00a5ef2638.png">
Clicking the add button on this form sends us to this route, which isn't defined:
https://hyphy.demo.hydrainabox.org/admin/groups/1/users/add?locale=en

**Comment by mjgiarlo** [comment]
Replaced by https://github.com/projecthydra-labs/hyku/issues/837
