### ISSUE TITLE
before_action in BreadcrumbsForWorks doesn't belong

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyrax#512]
Seems this belongs in a more appropriate place:
```ruby
        before_action :save_permissions, only: :update
```

**Comment by mjgiarlo** [comment]
I believe it was here before the breadcrumb extraction in Hyrax: https://github.com/projecthydra-labs/hyrax/blob/master/app/controllers/concerns/hyrax/works_controller_behavior.rb
