### ISSUE TITLE
FlipFlop 2.3 breaks the admin features view.

### ISSUE THREAD

**Issue by jonathandixon** [projecthydra-labs/hyrax#522]
### Descriptive summary

The `Flipflop::FeaturesController::FeaturesPresenter.features` method was removed when grouped features were introduced, see [FlipFlop #17](https://github.com/voormedia/flipflop/issues/17). 

This causes the error `undefined method 'features' for #<Flipflop::FeaturesController::FeaturesPresenter:0x007f0975555818>` on line 19 of `app/views/hyrax/admin/features/index.html.erb`

**Comment by mjgiarlo** [comment]
I suggest we fix this in the Sufia `master` branch and merge that over to Hyrax.

**Comment by mjgiarlo** [comment]
Written up as https://github.com/projecthydra/sufia/issues/3117. Thanks, @jonathandixon.
