### ISSUE TITLE
Stop displaying editable content blocks inline

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra-labs/hyrax#538]
Hyrax should do what Hyku does, where editing of all editable content blocks and pages is done in the dashboard rather than inline. This brings administrative functions together and results in a nicer UI for administrative users. Extract this from Hyku.

This should be a new page on the admin dashboard.

**Comment by jcoyne** [comment]
Do this prior to tackling #406

**Comment by cjcolvar** [comment]
:+1: As a hyrax adopter that never used Sufia or CurationConcerns, the in-line content blocks on the homepage confused everyone the first time they logged in as an admin.  They thought the editable red bar note was actually an error.

**Comment by mjgiarlo** [comment]
A PR for this is now ready for review.
