### ISSUE TITLE
Removing AdminSet manager does not update edit_access in solr doc

### ISSUE THREAD

**Issue by elrayle** [projecthydra-labs/hyrax#570]
### Descriptive summary

When a user is removed as manger of an AdminSet via the UI, the user is not removed from the edit_access_person_ssim in the solr doc.  (Likely the same is true for group managers.)

### Expected behavior

When a manager is removed, the edit_access_person/group_ssim in the solr doc for the AdminSet should have the user's id removed.

### Actual behavior

When a manager is removed, the edit_access_person_ssim is unchanged.

#### Prerequisite:
1. Create 1 admin user and 1 non-admin user
1. Create an Admin Set
  1. Login as an admin user
  1. Create an Admin Set and Save
1. Add non-admin user as a manager
  1. Click the Participants tab
  1. Add Participants -> Add user: -> set to non-admin user
  1. Set role to Manager
  1. Click Add button
  1. **VERIFY:** Check solr document for the new Admin Set in Solr and verify that the selected user is in the `edit_access_person_ssim` list.

#### Reproduce the issue

1. Remove the user as manager
  1. From the Participants tab, click the Remove button next to the non-admin user just added
  1. **NOTICE:** Check solr document for the Admin Set in Solr and notice that the selected user is still in the `edit_access_person_ssim` list.

**EXPECTED:** I would expect the `edit_access_person_ssim` to no longer include the removed manager.

**Comment by jcoyne** [comment]
@elrayle were you testing before or after this was merged? https://github.com/projecthydra-labs/hyrax/pull/567

**Comment by elrayle** [comment]
I took the latest this morning.  I still see the described behavior.

**Comment by jcoyne** [comment]
@elrayle thanks for checking. I'll have a look.
