### ISSUE TITLE
unable to download a file as expected in Chrome

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyrax#598]
I'm using Chrome Version 57.0.2987.110

No matter how I try to download a file from Hyrax/Hyku (eg, any button labeled "Download"), the file loads in a separate tab instead of initiating the download process (whether by prompt for confirmation or auto-download)

**Comment by darrenleeweber** [comment]
I'll try to replicate this bug using Chrome `Version 58.0.3029.110 (64-bit)` (on my Ubuntu 16.04 development VM).

**Comment by darrenleeweber** [comment]
After using developer tools to remove the `target="_blank"`, then Chrome downloads the image as binary data into the current window/tab - it's not pretty.

**Comment by darrenleeweber** [comment]
There are some forum comments requesting additional download features for Chrome, e.g.
https://productforums.google.com/forum/#!topic/chrome/np85LhaFIT0

**Comment by darrenleeweber** [comment]
@jcoyne comments in slack:

I suspect you have to fix it here: https://github.com/projecthydra/hydra-head/blob/master/hydra-core/app/controllers/concerns/hydra/controller/download_behavior.rb

Specifically: https://github.com/projecthydra/hydra-head/blob/master/hydra-core/app/controllers/concerns/hydra/controller/download_behavior.rb#L77
  - switch `inline` to `attachment` conditionally
  - here’s one project that did this: https://github.com/projecthydra-labs/hydradam/blob/master/app/controllers/downloads_controller.rb#L50

**Comment by mjgiarlo** [comment]
Thanks, @darrenleeweber!
