### ISSUE TITLE
Viewing a "pending" work not working, so unable to advance workflow status

### ISSUE THREAD

**Issue by laritakr** [projecthydra-labs/hyrax#605]
1. Add a work using mediated workflow.
2. View the pending work. 
3. Top menu will be mostly non-functional. 
4. The pending work page will not load fully - only loads title and status from the work. 

To get out of it, you have to go to the administration menu. Usually that makes the dropdowns work again (which makes this a real problem when working with a non-admin user).

Errors from console:

jquery_ujs.self-784a997….js?body=1:18 Uncaught Error: jquery-ujs has already been loaded!
    at Function.error (jquery.self-bd7ddd3….js?body=1:254)
    at jquery_ujs.self-784a997….js?body=1:18
    at jquery_ujs.self-784a997….js?body=1:555
error @ jquery.self-bd7ddd3….js?body=1:254
(anonymous) @ jquery_ujs.self-784a997….js?body=1:18
(anonymous) @ jquery_ujs.self-784a997….js?body=1:555
jquery.dataTables.bootstrap.self-131f130….j…:17 Uncaught Error: See almond README: incorrect module build, no module name
    at define (almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407)
    at jquery.dataTables.bootstrap.self-131f130….j…:17
    at jquery.dataTables.bootstrap.self-131f130….j…:42
define @ almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407
(anonymous) @ jquery.dataTables.bootstrap.self-131f130….j…:17
(anonymous) @ jquery.dataTables.bootstrap.self-131f130….j…:42
jquery.dataTables.self-f520d04….js?body=1:33 Uncaught Error: See almond README: incorrect module build, no module name
    at define (almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407)
    at jquery.dataTables.self-f520d04….js?body=1:33
    at jquery.dataTables.self-f520d04….js?body=1:60
define @ almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407
(anonymous) @ jquery.dataTables.self-f520d04….js?body=1:33
(anonymous) @ jquery.dataTables.self-f520d04….js?body=1:60
turbolinks.self-c5acd7a….js?body=1:7 Uncaught Error: See almond README: incorrect module build, no module name
    at define (almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407)
    at turbolinks.self-c5acd7a….js?body=1:7
    at turbolinks.self-c5acd7a….js?body=1:7
define @ almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407
(anonymous) @ turbolinks.self-c5acd7a….js?body=1:7
(anonymous) @ turbolinks.self-c5acd7a….js?body=1:7
imagesloaded.min.self-a1d38a7….js?body=1:8 Uncaught Error: See almond README: incorrect module build, no module name
    at define (almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407)
    at imagesloaded.min.self-a1d38a7….js?body=1:8
    at imagesloaded.min.self-a1d38a7….js?body=1:8
define @ almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407
(anonymous) @ imagesloaded.min.self-a1d38a7….js?body=1:8
(anonymous) @ imagesloaded.min.self-a1d38a7….js?body=1:8
typeahead.bundle.self-07ac315….js?body=1:10 Uncaught Error: See almond README: incorrect module build, no module name
    at define (almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407)
    at typeahead.bundle.self-07ac315….js?body=1:10
    at typeahead.bundle.self-07ac315….js?body=1:18
define @ almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407
(anonymous) @ typeahead.bundle.self-07ac315….js?body=1:10
(anonymous) @ typeahead.bundle.self-07ac315….js?body=1:18
masonry.min.self-5e03815….js?body=1:10 Uncaught Error: See almond README: incorrect module build, no module name
    at define (almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407)
    at masonry.min.self-5e03815….js?body=1:10
    at masonry.min.self-5e03815….js?body=1:10
define @ almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407
(anonymous) @ masonry.min.self-5e03815….js?body=1:10
(anonymous) @ masonry.min.self-5e03815….js?body=1:10
action_cable.self-5454023….js?body=1:595 Uncaught Error: See almond README: incorrect module build, no module name
    at define (almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407)
    at action_cable.self-5454023….js?body=1:595
    at action_cable.self-5454023….js?body=1:597
define @ almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407
(anonymous) @ action_cable.self-5454023….js?body=1:595
(anonymous) @ action_cable.self-5454023….js?body=1:597
openseadragon.self-77011f3….js?body=1:702 Uncaught Error: See almond README: incorrect module build, no module name
    at define (almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407)
    at openseadragon.self-77011f3….js?body=1:702
define @ almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407
(anonymous) @ openseadragon.self-77011f3….js?body=1:702
core.self-93be4d2….js?body=1:16 Uncaught Error: See almond README: incorrect module build, no module name
    at define (almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407)
    at core.self-93be4d2….js?body=1:16
    at core.self-93be4d2….js?body=1:22
define @ almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407
(anonymous) @ core.self-93be4d2….js?body=1:16
(anonymous) @ core.self-93be4d2….js?body=1:22
position.self-e693ced….js?body=1:16 Uncaught Error: See almond README: incorrect module build, no module name
    at define (almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407)
    at position.self-e693ced….js?body=1:16
    at position.self-e693ced….js?body=1:22
define @ almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407
(anonymous) @ position.self-e693ced….js?body=1:16
(anonymous) @ position.self-e693ced….js?body=1:22
effect.self-3acdb29….js?body=1:16 Uncaught Error: See almond README: incorrect module build, no module name
    at define (almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407)
    at effect.self-3acdb29….js?body=1:16
    at effect.self-3acdb29….js?body=1:22
define @ almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407
(anonymous) @ effect.self-3acdb29….js?body=1:16
(anonymous) @ effect.self-3acdb29….js?body=1:22
widget.self-c160224….js?body=1:16 Uncaught Error: See almond README: incorrect module build, no module name
    at define (almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407)
    at widget.self-c160224….js?body=1:16
    at widget.self-c160224….js?body=1:22
define @ almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407
(anonymous) @ widget.self-c160224….js?body=1:16
(anonymous) @ widget.self-c160224….js?body=1:22
menu.self-7abc1c9….js?body=1:20 Uncaught Error: See almond README: incorrect module build, no module name
    at define (almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407)
    at menu.self-7abc1c9….js?body=1:20
    at menu.self-7abc1c9….js?body=1:31
define @ almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407
(anonymous) @ menu.self-7abc1c9….js?body=1:20
(anonymous) @ menu.self-7abc1c9….js?body=1:31
effect-highlight.self-f922b71….js?body=1:18 Uncaught Error: See almond README: incorrect module build, no module name
    at define (almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407)
    at effect-highlight.self-f922b71….js?body=1:18
    at effect-highlight.self-f922b71….js?body=1:27
define @ almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407
(anonymous) @ effect-highlight.self-f922b71….js?body=1:18
(anonymous) @ effect-highlight.self-f922b71….js?body=1:27
mouse.self-c513294….js?body=1:19 Uncaught Error: See almond README: incorrect module build, no module name
    at define (almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407)
    at mouse.self-c513294….js?body=1:19
    at mouse.self-c513294….js?body=1:28
define @ almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407
(anonymous) @ mouse.self-c513294….js?body=1:19
(anonymous) @ mouse.self-c513294….js?body=1:28
autocomplete.self-3befc48….js?body=1:21 Uncaught Error: See almond README: incorrect module build, no module name
    at define (almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407)
    at autocomplete.self-3befc48….js?body=1:21
    at autocomplete.self-3befc48….js?body=1:33
define @ almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407
(anonymous) @ autocomplete.self-3befc48….js?body=1:21
(anonymous) @ autocomplete.self-3befc48….js?body=1:33
sortable.self-df2d80a….js?body=1:20 Uncaught Error: See almond README: incorrect module build, no module name
    at define (almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407)
    at sortable.self-df2d80a….js?body=1:20
    at sortable.self-df2d80a….js?body=1:31
define @ almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407
(anonymous) @ sortable.self-df2d80a….js?body=1:20
(anonymous) @ sortable.self-df2d80a….js?body=1:31
jquery.flot.selection.self-515ce0f….js?body…:348 Uncaught TypeError: Cannot read property 'plugins' of undefined
    at jquery.flot.selection.self-515ce0f….js?body…:348
    at jquery.flot.selection.self-515ce0f….js?body…:361
(anonymous) @ jquery.flot.selection.self-515ce0f….js?body…:348
(anonymous) @ jquery.flot.selection.self-515ce0f….js?body…:361
jquery.flot.time.self-d609941….js?body=1:419 Uncaught TypeError: Cannot read property 'plugins' of undefined
    at jquery.flot.time.self-d609941….js?body=1:419
    at jquery.flot.time.self-d609941….js?body=1:433
(anonymous) @ jquery.flot.time.self-d609941….js?body=1:419
(anonymous) @ jquery.flot.time.self-d609941….js?body=1:433
clipboard.self-8119efe….js?body=1:8 Uncaught Error: See almond README: incorrect module build, no module name
    at define (almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407)
    at clipboard.self-8119efe….js?body=1:8
    at clipboard.self-8119efe….js?body=1:8
define @ almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407
(anonymous) @ clipboard.self-8119efe….js?body=1:8
(anonymous) @ clipboard.self-8119efe….js?body=1:8
raphael-min.self-befd2ca….js?body=1:9 Uncaught Error: See almond README: incorrect module build, no module name
    at define (almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407)
    at raphael-min.self-befd2ca….js?body=1:9
    at raphael-min.self-befd2ca….js?body=1:9
define @ almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407
(anonymous) @ raphael-min.self-befd2ca….js?body=1:9
(anonymous) @ raphael-min.self-befd2ca….js?body=1:9
polyfill.self-e0c7113….js?body=1:10 Uncaught Error: only one instance of babel/polyfill is allowed
    at Object.<anonymous> (polyfill.self-e0c7113….js?body=1:10)
    at Object.1.188 (polyfill.self-e0c7113….js?body=1:13)
    at s (polyfill.self-e0c7113….js?body=1:1)
    at e (polyfill.self-e0c7113….js?body=1:1)
    at polyfill.self-e0c7113….js?body=1:1
(anonymous) @ polyfill.self-e0c7113….js?body=1:10
1.188 @ polyfill.self-e0c7113….js?body=1:13
s @ polyfill.self-e0c7113….js?body=1:1
e @ polyfill.self-e0c7113….js?body=1:1
(anonymous) @ polyfill.self-e0c7113….js?body=1:1
time-elements.self-713bc49….js?body=1:595 Uncaught DOMException: Failed to execute 'registerElement' on 'Document': Registration failed for type 'relative-time'. A type with that name is already registered.
    at http://localhost:3000/assets/time-elements.self-713bc4971e43ed6d469545ce9647ca4ca983752d89fe091fe823234f7eba753e.js?body=1:595:41
    at http://localhost:3000/assets/time-elements.self-713bc4971e43ed6d469545ce9647ca4ca983752d89fe091fe823234f7eba753e.js?body=1:616:3
(anonymous) @ time-elements.self-713bc49….js?body=1:595
(anonymous) @ time-elements.self-713bc49….js?body=1:616
jquery.iframe-transport.self-6fdacce….js?bo…:19 Uncaught Error: See almond README: incorrect module build, no module name
    at define (almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407)
    at jquery.iframe-transport.self-6fdacce….js?bo…:19
    at jquery.iframe-transport.self-6fdacce….js?bo…:27
define @ almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407
(anonymous) @ jquery.iframe-transport.self-6fdacce….js?bo…:19
(anonymous) @ jquery.iframe-transport.self-6fdacce….js?bo…:27
tmpl.self-a8d99bb….js?body=1:79 Uncaught Error: See almond README: incorrect module build, no module name
    at define (almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407)
    at tmpl.self-a8d99bb….js?body=1:79
    at tmpl.self-a8d99bb….js?body=1:87
define @ almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407
(anonymous) @ tmpl.self-a8d99bb….js?body=1:79
(anonymous) @ tmpl.self-a8d99bb….js?body=1:87
jquery.fileupload-process.self-b6c54bb….js?…:20 Uncaught Error: See almond README: incorrect module build, no module name
    at define (almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407)
    at jquery.fileupload-process.self-b6c54bb….js?…:20
    at jquery.fileupload-process.self-b6c54bb….js?…:33
define @ almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407
(anonymous) @ jquery.fileupload-process.self-b6c54bb….js?…:20
(anonymous) @ jquery.fileupload-process.self-b6c54bb….js?…:33
jquery.fileupload-ui.self-5c30a23….js?body=1:20 Uncaught Error: See almond README: incorrect module build, no module name
    at define (almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407)
    at jquery.fileupload-ui.self-5c30a23….js?body=1:20
    at jquery.fileupload-ui.self-5c30a23….js?body=1:41
define @ almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407
(anonymous) @ jquery.fileupload-ui.self-5c30a23….js?body=1:20
(anonymous) @ jquery.fileupload-ui.self-5c30a23….js?body=1:41
jquery.fileupload.self-c6cbb0b….js?body=1:20 Uncaught Error: See almond README: incorrect module build, no module name
    at define (almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407)
    at jquery.fileupload.self-c6cbb0b….js?body=1:20
    at jquery.fileupload.self-c6cbb0b….js?body=1:34
define @ almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407
(anonymous) @ jquery.fileupload.self-c6cbb0b….js?body=1:20
(anonymous) @ jquery.fileupload.self-c6cbb0b….js?body=1:34
jquery.fileupload-validate.self-950050c….js…:19 Uncaught Error: See almond README: incorrect module build, no module name
    at define (almond.self-3921caa456bd6df6e95fef599cb2bf043bab471b22c8608fc49a7d8f5ca1e46d.js:407)
    at jquery.fileupload-validate.self-950050c….js…:19
    at jquery.fileupload-validate.self-950050c….js…:32

**Comment by laritakr** [comment]
If left long enough, the dropdowns eventually come back. But the "pending work" page only loads the title and status so I've found no way to move it along in the workflow.

![screen shot 2017-03-21 at 1 08 19 pm](https://cloud.githubusercontent.com/assets/17851674/24160216/95107066-0e37-11e7-8b78-1e1f1a5b4712.png)

**Comment by jcoyne** [comment]
@laritakr javascript fixed in #618.  The other problem is probably that you don't have the approving role for this workflow. see #621.
