### ISSUE TITLE
icons in buttons within .main-header are too dark

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyrax#611]
<img width="254" alt="screen shot 2017-03-21 at 10 23 18 am" src="https://cloud.githubusercontent.com/assets/92044/24154954/8074b5b6-0e20-11e7-8cd0-308f8b9e40a2.png">

cc @ggeisler

**Comment by mjgiarlo** [comment]
@jcoyne This is not the case in Hyku demo instance. Close, or do we need to port Hyku styles to Hyrax?

**Comment by jcoyne** [comment]
Maybe this is already fixed? @ggeisler?

**Comment by ggeisler** [comment]
I think it might have been fixed as part of another ticket, but am not positive. Not running Hyrax at the moment, but if anyone is and doesn't see the issue, I'd assume it was fixed.

**Comment by mjgiarlo** [comment]
I'm not seeing anything specific in Hyku (e.g., [here](https://github.com/projecthydra-labs/hyku/blob/master/app/assets/stylesheets/hyku.scss)) that makes me think this was fixed in Hyku only. Closing.

Thanks, @jcoyne @ggeisler
