### ISSUE TITLE
Features can be flipped off but not back on

### ISSUE THREAD

**Issue by cjcolvar** [projecthydra-labs/hyrax#632]
### Descriptive summary

Flipflop 2.3.0 released 23 days ago switched the param value used to commit from "on" to "1" which breaks flipping features back on.  Hyrax should either pin to flipflop 2.2.1, create an issue with flipflop, or update the view to use the new value for commit.

Flipflop code in question:
https://github.com/voormedia/flipflop/blob/master/app/controllers/flipflop/strategies_controller.rb#L17-L19

Hyrax submit button with "on" value:
https://github.com/projecthydra-labs/hyrax/blob/master/app/views/hyrax/admin/features/index.html.erb#L44

Commit in question:
https://github.com/voormedia/flipflop/commit/51cc858f3307003d16c15dd78ad8541941bd3274#diff-50f28c8e6f2ebbc297d52daa88bac730

**Comment by jcoyne** [comment]
https://github.com/voormedia/flipflop/issues/20

**Comment by jcoyne** [comment]
Fixed by Flipflop 2.3.1
