### ISSUE TITLE
permission template not found

### ISSUE THREAD

**Issue by elrayle** [projecthydra-labs/hyrax#641]
### Descriptive summary

App generated by engine_cart gets `permission template not found` error when saving a GenericWork.

### Expected behavior

To be able to save a work.

### Actual behavior

Error when saving a work.

### Steps to reproduce the behavior

1. clone hyrax
1. `rake engine_cart:clean`
1. start rails server in .internal_test app
1. Works -> New Work
1. Fill in required metadata and add a file
1. Save

Gets error:  Couldn't find Hyrax::PermissionTemplate

### Related work

The same happens when you generate a hyrax app following the README instructions.

**Comment by elrayle** [comment]
<img width="1156" alt="image" src="https://cloud.githubusercontent.com/assets/6855473/24297639/d5bf0886-1079-11e7-96d7-6dbd4ba3804a.png">

**Comment by elrayle** [comment]
I'm hoping there is something off in my environments, or there is a setup step that is missing.  Anyone else seeing this?

**Comment by elrayle** [comment]
Steps to create a hyrax app that got rid of this error...

1) Install prerequisite software including nodejs or some other javascript runtime
2) run `rails new` with template
3) if using rubyracer for javascript runtime, uncomment in Gemfile and bundle install  (Not needed if using nodejs.  No gem needed for nodejs.)
4) start servers (solr, fedora, message queue) - several options for message queue, see doc
5) load workflows with `rake hyrax:workflow:load`
6) create default admin set with `rake hyrax:default_admin_set:create`
7) NOW - generate a work type
8) start server and everything should work

**Comment by tap87** [comment]
@elrayle 
I had to run step 6 before step 5 to load the workflows. Can you confirm that and change the steps accordingly?

**Comment by mjgiarlo** [comment]
That makes sense to me, @tap87

**Comment by elrayle** [comment]
NOTE: If doing local testing, replace step 2 with `rake engine_cart:generate` which creates .internal_test directory with a test app.

If you have made changes and want to regenerate the test app, run `rake engine_cart:clean` before running generate.
