### ISSUE TITLE
/users/sign_in fails on POST using JSON

### ISSUE THREAD

**Issue by revgum** [projecthydra-labs/hyrax#666]
Devise expects the controller to respond_to json but `Hyrax::Controller` doesn't have this explicitly set. 

Two approaches I've tested that work, but have different implications.

1. Just tell `Hyrax::Controller` to respond to json by adding `respond_to :html, :json` to the `included` block. I've tested this locally and it works as expected with user login using json. 

2. Create a `Hyrax::SessionsController` to handle it.

```
module Hyrax
  class SessionsController < Devise::SessionsController
    respond_to :html, :json
  end
end
```

Along with this new controller, Hyrax would need a route update. This approach was also tested locally and works.
```  
devise_for :users, skip: [:sessions]
  as :user do
    get '/users/sign_in', to: 'hyrax/sessions#new', as: :new_user_session
    post '/users/sign_in', to: 'hyrax/sessions#create', as: :user_session
    get '/users/sign_out', to: 'hyrax/sessions#destroy', as: :destroy_user_session
  end
```

Looking for thoughts/feedback.

**Comment by jcoyne** [comment]
I think this should be a local application concern (possibly a wiki post) because devise is just a default. People may swap it out for omniauth or something else.

**Comment by revgum** [comment]
Gotcha.
