### ISSUE TITLE
Submitting a "Private" work through mediated deposit results in the depositor not being able to view their own work

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyrax#672]
Currently a mediated work strips all access for the depositor, but it probably ought to degrade the depositors access from edit to view.

**Comment by jcoyne** [comment]
@hannahfrost @mjgiarlo Can you confirm that my suggested fix is the desired behavior?

**Comment by hannahfrost** [comment]
@jcoyne Desired behavior is depositor access level is view while it is in active workflow. 

Once "approved" and not in active workflow, the access level is back to edit?

**Comment by vantuyls** [comment]
i think once "approved" the workflow configuration should define the depositor's access level. @hannahfrost's recommendation might be appropriate for the default, but we (community) have use cases where once approved the depositor should still only have view access.
