### ISSUE TITLE
Should an AdminSet manager automatically get the approving roles for the workflows?

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyrax#673]
This would save an extra setup step. 
<img width="1440" alt="screen shot 2017-03-29 at 1 17 55 pm" src="https://cloud.githubusercontent.com/assets/92044/24475009/7172c878-1483-11e7-83ee-83358292c8d0.png">

**Comment by hannahfrost** [comment]
Yes. See #692

**Comment by jeremyf** [comment]
Who are the admin set managers? How is that determined?

**Comment by jcoyne** [comment]
@jeremyf admin set managers as added here:
<img width="1440" alt="screen shot 2017-03-29 at 1 03 55 pm" src="https://cloud.githubusercontent.com/assets/92044/24676628/567e6d4a-1949-11e7-8da4-7849725c7c26.png">

**Comment by jeremyf** [comment]
And the Role drop-down…are those populated from Sipity::Role?

**Comment by jcoyne** [comment]
@jeremyf nope, that's a hard coded thing. So, this form would only work if you're using the provided workflows.
