### ISSUE TITLE
Share tab does not display, if the defaulted admin set is a single-step workflow

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyrax#676]
If I switch to another admin set, and then switch back, then it shows up.

**Comment by atz** [comment]
Can you give more context?  What page are you looking at?  And item or collection?

**Comment by jcoyne** [comment]
<img width="451" alt="screen shot 2017-04-05 at 8 03 12 pm" src="https://cloud.githubusercontent.com/assets/92044/24733076/f087cde0-1a3a-11e7-9010-87e43227d1fc.png">
@atz the share tab here.  Anyways it's fixed in #719.
