### ISSUE TITLE
Is there a reason secondary_terms are an instance method

### ISSUE THREAD

**Issue by cam156** [projecthydra-labs/hyrax#683]
### Descriptive summary
In Hyrax master is there a reason why terms is a class method and secondary_terms is an instance method?  It would be nice if they were all class methods unless there was some rationale for doing it in a mixed way.

https://github.com/projecthydra-labs/hyrax/blob/master/app/forms/hyrax/forms/work_form.rb#L65

**Comment by jcoyne** [comment]
It's not something new to Hyrax.  This was added in Sufia 7.0 https://github.com/projecthydra/sufia/commit/27d58780aa81387ec25c16968edcf7fb2b80784d

**Comment by cam156** [comment]
@jcoyne So I am hearing It would be ok for them to be a class method with a deprecated instance method?

**Comment by jcoyne** [comment]
@cam156 I'd rather we make them all instance methods.  That way one can make decisions about what to present based on who the current user is.

**Comment by jcoyne** [comment]
@cam156 FWIW, terms is both a class method and and instance method:

```
> Hyrax::Forms::WorkForm.new(GenericWork.new,nil,nil).terms
=> [:title, :creator, :contributor, :description, :keyword, :license, :rights_statement, :publisher, :date_created, :subject, :language, :identifier, :based_near, :related_url, :representative_id, :thumbnail_id, :files, :visibility_during_embargo, :embargo_release_date, :visibility_after_embargo, :visibility_during_lease, :lease_expiration_date, :visibility_after_lease, :visibility, :ordered_member_ids, :source, :in_works_ids, :member_of_collection_ids, :admin_set_id]
```

**Comment by hackmastera** [comment]
> make them all instance methods. That way one can make decisions about what to present based on who the current user is.

+1
