### ISSUE TITLE
Automatically give user workflow role to user when they are added as participant to admin set

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyrax#692]
### Descriptive summary

As a user is added as a participant to an admin set in a given role, the associated workflow role needs to be automatically associated with the user

### Rationale

This functionality makes it possible for the user to participate in the admin set in their specified role without any further configuration.

### Expected behavior

As the manager of an Admin Set, after I add Participants to that Admin Set, those users can work in the Admin Set in the roles that I specified without any further configuration.

### Actual behavior

Currently the manager needs to use the "Workflow Roles" screen to actually grant the workflow roles. We want to eliminate this step (and the need to display this screen).

**Comment by jeremyf** [comment]
This behavior is informed by #674
