### ISSUE TITLE
Generator is creating bad routes for atlas

### ISSUE THREAD

**Issue by cam156** [projecthydra-labs/hyrax#693]
### Descriptive summary

In Master when you create the test app it creates bad routes for Atlas.  If I had to hazard a guess the plural to singular is causing the atla instead of the atlas.  I do not see the same behavior when I generate a class not ending in `s`.

<img width="1008" alt="screen shot 2017-04-03 at 2 00 43 pm" src="https://cloud.githubusercontent.com/assets/1599081/24623334/115516b6-1876-11e7-82d5-f27ef888d5ca.png">

### Expected behavior

should get routes for atlas

### Actual behavior

get routes for atla

### Steps to reproduce the behavior

1. run rake engin_cart:generate
1. cd .internal_test_app
1. run rake routes

### Related work

Link to related tickets or prior related work here.

**Comment by jcoyne** [comment]
This is the expected behavior of rails. See http://api.rubyonrails.org/classes/ActiveSupport/Inflector/Inflections.html#method-i-irregular

**Comment by mjgiarlo** [comment]
At the very least, perhaps we should include a warning in the documentation that some weird things might happen depending on how the new curation concern is named, and steps to achieve the desired effect?

**Comment by atz** [comment]
I don't think this would warrant more than a parenthetical explanation.  It is a known thing in rails.  If we care about the pluralization of "atlases" we could add an initializer like Justin mentioned:
```ruby
ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.irregular 'atlas', 'atlases'
end
```

The point of having generated the second work type was to test all the behaviors that were suppressed when only one work type existed.  I don't think we rely on the name of the routes for anything.

**Comment by mjgiarlo** [comment]
After talking with @cam156 some more about this issue, the workaround I submitted does not address the underlying bug, which is that Rails and Hyrax have different assumptions: Rails makes a guess as to whether the given name is singular or plural, and Hyrax assumes it's singular. Hyrax should either defer to Rails, or Hyrax should coerce the generation into assuming the given work type name is singular.
