### ISSUE TITLE
Template installer should run `rails generate rspec:install`

### ISSUE THREAD

**Issue by bess** [projecthydra-labs/hyrax#708]
### Descriptive summary

Re: Hyrax 1.0.0.rc1 

### Rationale

When installed via the template installer, after you generate a new work type, rspec tests are generated but they won't run because rails_helper.rb doesn't exist. 

### Expected behavior

The template should run `rails generate rspec:install` to create all the files necessary to run rspec

### Actual behavior

```
paz:laevigata bess$ bundle exec rake spec
/Users/bess/.rvm/rubies/ruby-2.3.3/bin/ruby -I/Users/bess/.rvm/gems/ruby-2.3.3@hyrax/gems/rspec-core-3.5.4/lib:/Users/bess/.rvm/gems/ruby-2.3.3@hyrax/gems/rspec-support-3.5.0/lib /Users/bess/.rvm/gems/ruby-2.3.3@hyrax/gems/rspec-core-3.5.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
/usr/local/projects/hyrax/laevigata/spec/actors/hyrax/actors/etd_actor_spec.rb:3:in `require': cannot load such file -- rails_helper (LoadError)
```

### Steps to reproduce the behavior

1. Install a new app via the template installer
1. Create a new work type
1. Attempt to run test suite via `rake spec` or `rspec spec`

**Comment by jcoyne** [comment]
I believe this should be moved to the hydra-head repository as it is the generator that installs rspec-rails: https://github.com/projecthydra/hydra-head/blob/master/hydra-core/lib/generators/hydra/head_generator.rb#L28

**Comment by mjgiarlo** [comment]
@bess What say you? Close and move to hydra-head?

**Comment by bess** [comment]
Sure, that sounds like a fine solution.

**Comment by mjgiarlo** [comment]
Copied to https://github.com/projecthydra/hydra-head/issues/409

Thanks!
