### ISSUE TITLE
Appearances config for link color seems to be global rather than just footer

### ISSUE THREAD

**Issue by ggeisler** [projecthydra-labs/hyrax#727]
@jcoyne Can you double-check the updates you made in #715? As shown in my screenshots in that PR the goal was only to change the link color in the footer (because of the dark background) but it appears that the updates affected the link color globally. I don't think we want that.

![hyrax](https://cloud.githubusercontent.com/assets/101482/24774439/be3faf54-1acd-11e7-9e5c-f6c7987300d8.png)

Let me know if I'm misunderstanding something.

**Comment by jcoyne** [comment]
@ggeisler I added two settings one for the footer link color and one for the global link color. You can set both here: http://localhost:3000/admin/appearance

**Comment by ggeisler** [comment]
Yeah, I was just looking into that and now see what you did. I'm going to set the default link color to be the Bootstrap default and all should be fine. PR in a minute.

**Comment by jcoyne** [comment]
@ggeisler this may also help. The link color wasn't saving: https://github.com/projecthydra-labs/hyrax/pull/729
