### ISSUE TITLE
Non-admin user can not submit a work

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyrax#753]
Pressing the submit button goes to a 404 page. Seems to work when logged in as an admin though.

**Comment by jcoyne** [comment]
Waiting on  https://github.com/projecthydra-labs/hyku/pull/939 for further diagnosis.

**Comment by mjgiarlo** [comment]
Unblocked.

**Comment by jcoyne** [comment]
This is confusing.
Admin gets this:
```
10.0.4.194 - - [11/Apr/2017:20:34:42 +0000] "POST /concern/generic_works?locale=en HTTP/1.1" 302 176 "https://hyphy.demo.hydrainabox.org/concern/generic_works/new?locale=en" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0" "97.116.190.118"
```

Regular user gets:
```
10.0.4.194 - - [11/Apr/2017:20:32:05 +0000] "POST /concern/generic_works?locale=en HTTP/1.1" 404 1564 "https://hyphy.demo.hydrainabox.org/concern/generic_works/new?locale=en" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0" "97.116.190.118"
```

**Comment by jcoyne** [comment]
Looks like this was just a problem in my version, which was created before active_workflow was a thing.  Not a problem in a fresh instance.

**Comment by mjgiarlo** [comment]
@jcoyne does this mean we ought to capture this in release notes somewhere?

**Comment by jcoyne** [comment]
@mjgiarlo only if you created an admin set before admin sets automatically loaded workflows.  Sometime back in January?

**Comment by mjgiarlo** [comment]
:ok_hand:
