### ISSUE TITLE
Ldp::Gone error after deleting a work or files from a work

### ISSUE THREAD

**Issue by tap87** [projecthydra-labs/hyrax#762]
When I delete a work or file (delete link in dropdown, or delete button), I get an Ldp::Gone error.
Hyrax master branch

Expected behavior
After deleting a work, it should redirect to the dashboard
After deleting a file from a work, it should redirect to the work

Actual behavior
Ldp::Gone error

Steps to reproduce the behavior

1. Create a new work
1. Delete the work (or a file in the work)

Related work
Same [issue](https://github.com/projecthydra-labs/hyku/issues/940) in Hybox

**Comment by mjgiarlo** [comment]
@tap87 Thanks for writing up this ticket, Tahir. Are you planning to troubleshoot it and write up a PR? (I'm wondering how much to read into you self-assigning this issue.)

**Comment by tap87** [comment]
Thanks @mjgiarlo This is the same issue as reported in Hybox (https://github.com/projecthydra-labs/hyku/issues/940). I was on slack and @jcoyne asked me if I wanted to work on it which is why I self-assigned this one. I am planning to create a PR soon. Feel free to reassign if you think otherwise

**Comment by mjgiarlo** [comment]
Have at it, @tap87! Thank you.

**Comment by tap87** [comment]
@mjgiarlo @jcoyne Should the fix be against the master or the 1-0-stable branch?

**Comment by atz** [comment]
Probably best to target master and then backport to stable if necessary.

**Comment by mjgiarlo** [comment]
@tap87 :+1: to what @atz suggested!
