### ISSUE TITLE
Create Chinese internationalization locale.

### ISSUE THREAD

**Issue by hweng** [projecthydra-labs/hyrax#793]
### Descriptive summary

Create a Chinese locale file to live alongside the Spanish and English instances in the Hyrax repository.

### Rationale

The Hydra community has been making strides at internationalization efforts lately, and now support both Spanish and English. UCSD would like to contribute a Chinese locale to enable browsing by native speakers.

### Expected behavior

Following the creation of the Chinese locale yaml file, the drop-down menu for locale that currently allows a selection of English and Spanish should include an option for Chinese.

### Related work

Link to related tickets or prior related work here.
https://github.com/ucsdlib/horton/issues/61

**Comment by mjgiarlo** [comment]
Yes, please! Love this.
