### ISSUE TITLE
Rails Init Template Versions

### ISSUE THREAD

**Issue by no-reply** [projecthydra-labs/hyrax#796]
We currently ask users to use the [template on the `master`](https://raw.githubusercontent.com/projecthydra-labs/hyrax/master/template.rb) branch when calling `rails new`. This probably won't work in the long run; e.g. if I'm installing a Hyrax 1.0 alpha a year from now, it's unlikely that the template on `master` will still be acceptable. Can we communicate a better versioning scheme for these templates in the README?

### Rationale

I'm writing up a playbook documenting best practices for starting a new hyrax project and don't want to reproduce--or even link to--a fragile bit of documentation.

**Comment by jcoyne** [comment]
Why would anyone use a template to install a version less than the most recent major? That seems implausible to me. I don't want to invent more process without a realistic use case

**Comment by no-reply** [comment]
> Why would anyone use a template to install a version less than the most recent major?

The current case has us only installing the most recent `master`, not the most recent major. This is the state of affairs I'm concerned about.

**Comment by jcoyne** [comment]
Doesn't the most recent template install 1.0.0.rc1?

**Comment by no-reply** [comment]
Yes. However, it contains code that is subject to change independent of version releases.

If there's a general policy that the `master` template cannot change until a new version is released, I guess the risk is minimal. Otherwise, any maintenance to the template code may break installation, yes?

It seems like directing users to install a tagged version of the file would be more stable and more flexible. If that's wrong, feel free to close it.

**Comment by mjgiarlo** [comment]
@no-reply Is this the same thing we've been kicking around in https://github.com/projecthydra-labs/hyrax/issues/492?

**Comment by no-reply** [comment]
Looks like. Closing as duplicate of #492.

Thanks @mjgiarlo and @jcoyne.

**Comment by mjgiarlo** [comment]
@no-reply do toss a comment on #492 to reflect your druthers, pls! I'd like to wrap that issue up soon.
