### ISSUE TITLE
500 Internal Sever Error when versioning a work.

### ISSUE THREAD

**Issue by straleyb** [projecthydra-labs/hyrax#798]
### Descriptive summary

This problem exists in the Hyrax master branch and I assume all other branches derived from it. The bug is that there is a 500 internal server error being thrown when attempting to version an ingested work. Inspecting the logs showed that there was an `ArgumentError (wrong number of arguments (1 for 2))` for the method `#ingest_file` in the `file_actor`. This method is being called from the `file_sets_actor` and only calling it using one argument instead of the two that it requires. 

Here is the link to the line that is faulty.
https://github.com/projecthydra-labs/hyrax/blob/master/app/actors/hyrax/actors/file_set_actor.rb#L89

### Rationale

As a user, I would like to version my work if continued work is being done on an ingested item.

### Expected behavior

When a work is versioned, it should ingest a new work, with updated information about that work. A user should be able to see the older and newer versions of a work and follow how many times it has been edited and updated.

### Actual behavior

500 Internal Server Error

### Steps to reproduce the behavior

1. Ingest a work.
2. Version the work.

**Comment by mjgiarlo** [comment]
Once we have a PR for this in `master`, we should backport a fix to `1-0-stable`.

Thanks for reporting, @straleyb!

**Comment by jonathandixon** [comment]
This appears to be fixed by this commit db874069fb0d5586109c1f404c21e36195f3f4b3

**Comment by mjgiarlo** [comment]
Thank you, @jonathandixon. I just backported this to `1-0-stable`: https://github.com/projecthydra-labs/hyrax/pull/1004

I'm closing this. Pls re-open if you're still seeing this behavior.
