### ISSUE TITLE
Fog reference causes exception at runtime

### ISSUE THREAD

**Issue by atz** [projecthydra-labs/hyrax#802]
Fog is not a dependency of Hyrax, but we try to sniff for it anyway:
https://github.com/projecthydra-labs/hyrax/blame/v1.0.0.rc1/app/jobs/attach_files_to_work_job.rb#L29

This causes exceptions to be thrown at job runtime:
https://app.honeybadger.io/projects/48327/faults/33327615#notice-summary

The error would have been discoverable with tests, but the testing arbitrarily defined the namespace in question (something that doesn't happen in production!):
https://github.com/projecthydra-labs/hyrax/blob/v1.0.0.rc1/spec/jobs/attach_files_to_work_job_spec.rb#L28-L32

**Comment by atz** [comment]
Instead of trying to sniff `file.file` for a class that may or may not be loaded (or a range of possible CarrierWave abstractions), we should just ask it `file.file.respond_to?(:url)`, which is all we care about anyway.  Then this brittle, hazardous case statement can die.  

`import_url` should probably take the url instead of the file... since that is all it cares about.

**Comment by mjgiarlo** [comment]
We should backport any fix to `1-0-stable` as well.

**Comment by atz** [comment]
Backporting now.
