### ISSUE TITLE
Edit work page is missing breadcrumbs

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyrax#811]
As a depositor or administrative user, when I am on the Edit Work page, I would expect to see the breadcrumbs at the top of the main page area, indicating that this page falls within "Administration" like other related pages do, ie., "Home / Administration / Works / Edit"

![screenshot 2017-04-20 16 46 39](https://cloud.githubusercontent.com/assets/1801076/25256984/a206f96a-25e9-11e7-82f3-8809e65ea581.png)

**Comment by darrenleeweber** [comment]
Does this bug describe required behavior in HyKu? Or is this is an expectation of a generic Hyrax app, but this behavior is deliberately modified by HyKu?  (Just checking, assuming the former.)

**Comment by atz** [comment]
Based on what I'm seeing today, I'm calling this one fixed in Hyrax.  Please open a Hyku ticket if the problem persists there!
![screen shot 2017-05-10 at 2 33 25 pm](https://cloud.githubusercontent.com/assets/109954/25922350/c0b8b598-358d-11e7-8469-8f08f448ae16.png)

**Comment by mjgiarlo** [comment]
@atz @darrenleeweber I can confirm this is still an issue in Hyku. I'll copy and paste this issue over there.
