### ISSUE TITLE
Inconsistent terminology: Administrative Sets vs Collections

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyrax#830]
Sidebar has Administrative Sets and Collections
<img width="262" alt="screen shot 2017-04-24 at 4 39 40 pm" src="https://cloud.githubusercontent.com/assets/92044/25359924/c342f978-290c-11e7-84ce-b96adf8c9891.png">

Dashboard has "Administrative Sets" listed but calls them "Collections"
<img width="1082" alt="screen shot 2017-04-24 at 4 39 34 pm" src="https://cloud.githubusercontent.com/assets/92044/25359946/d9ca11e0-290c-11e7-95c9-9d6ee2b77058.png">

**Comment by hannahfrost** [comment]
That UI should be corrected to refer to Administrative Sets in both cases.

**Comment by mjgiarlo** [comment]
@hannahfrost Does that also mean #844 and #846 should use the label "Administrative Sets" instead of "Collections"

**Comment by hannahfrost** [comment]
In several side discussions in the past, @ggeisler and I have considered this matter. Our thinking is that the public users should not see "administrative" describing any set or collection in the repository. It's all collections to them. The distinction should be made to logged in users in the "administrative" side of the app. 

It's worth noting that this same question/issue is surfacing in the Display Sets UI/UX working group. I _think_ there is, or ultimately will be, fairly wide support for morphing the existing concept of User Collection to become Display Set and ultimately referring to this all stuff -- admin sets included -- as "collections" in the public facing view.

**Comment by mjgiarlo** [comment]
OK! Thanks, @hannahfrost.

**Comment by mjgiarlo** [comment]
Closed by https://github.com/projecthydra-labs/hyrax/pull/912
