### ISSUE TITLE
'Share Your Work' button only works with multiple work types

### ISSUE THREAD

**Issue by rotated8** [projecthydra-labs/hyrax#835]
### Descriptive summary

When a user is logged in, the 'Share Your Work' button does nothing unless more than one work type has been generated.

### Expected behavior

The button takes me to the create page for the one existing work type.

### Actual behavior

The button goes nowhere.

### Steps to reproduce the behavior

1. Set up a repository with one work type.
1. Create an account and log in.
1. Click the 'Share Your Work' button on the homepage.

**Comment by jcoyne** [comment]
Affects 1.0.0.rc1
