### ISSUE TITLE
Logging out results in NoMethodError in Hyrax::Homepage#index

### ISSUE THREAD

**Issue by bess** [projecthydra-labs/hyrax#845]
### Descriptive summary

Using Hyrax 1.0.0.rc1, when I am logged in as any user, when I go to the menu in the top right corner and choose the "Logout" menu option, it results in an error page. 

### Rationale

If people are using this application at a public computer, we want them to be able to log out of their account. As a developer, I also need to be able to log out so I can log back in as a different user. 

### Expected behavior

I expect the application to log me out and return me to the main screen

### Actual behavior

I get an error message (see attached screen shot for stack trace)
```
NoMethodError in Hyrax::Homepage#index
Showing /usr/local/projects/hyrax/laevigata/app/views/hyrax/homepage/index.html.erb where line #12 raised:

undefined method `dashboard_path' for #<ActionDispatch::Routing::RoutesProxy:0x007fdae4135da0>
Did you mean?  dashboard_works_path
Extracted source (around line #12):
              
        <% end %>
      <% else %>
        <%= link_to hyrax.dashboard_path,
          class: "btn btn-primary btn-lg" do %>
          <i class="glyphicon glyphicon-upload"></i> <%= t('hyrax.share_button') %>
        <% end %>
```
Additionally, after this error is produced, the application stops responding to new requests at the root url.
![screen shot 2017-04-26 at 1 24 54 pm](https://cloud.githubusercontent.com/assets/65608/25448353/26095b4a-2a86-11e7-8e04-84919d617e44.png)

### Steps to reproduce the behavior

1. Generate a hyrax application
1. Log in as a user
1. Click the top right menu (the one showing your email address)
1. Choose the "Logout" menu item

**Comment by jcoyne** [comment]
It looks like that route should be `dashboard_index_path` in Hyrax 1.0. (`dashboard_path` is correct for 2.0)

**Comment by rotated8** [comment]
This is my fault. I copied a view from the wrong Hyrax branch.

**Comment by mjgiarlo** [comment]
@rotated8 Good eye. Do you have cycles to toss up a PR?

**Comment by bess** [comment]
Looks like there is no fix needed. We are running a 1.0.0.rc1 release, but @rotated8 accidentally copied a view from the master branch, which has an incompatible route, and I didn't realize that's how the problem had crept in. Problem solved!
