### ISSUE TITLE
About overriding the default breadcrumb behavior.

### ISSUE THREAD

**Issue by hweng** [projecthydra-labs/hyrax#847]
### Descriptive summary

Our UCSD DLDP requested to modify the breadcrumb to have objects include their parent collection in a breadcrumb trail.

For example, the expected breadcrumb behavior is: `My Dashboard/Animal Collection/ Bunny`, instead of default one: `My Dashboard/My Objects/Bunny`,

I think it can be done by overriding the #build_breadcrumbs method in hyrax:
https://github.com/projecthydra-labs/hyrax/blob/master/app/controllers/concerns/hyrax/breadcrumbs_for_works.rb#L17

To do that, the collection name and collection path need to be retrieved in work_controller. I tried that the following code can get the collection name:  
```
@document = ::SolrDocument.find(params[:id])
collection_name = @document[:member_of_collections_ssim].first
```

My question: Is there any available method in hyrax to parse the solr query?
For example: 
```
@doc = some_method(:q => 'has_model_ssim:Collection AND title_tesim:#{collection_name}’)
add_breadcrumb collection_name, hyrax.collection_path(@doc[:id])
```

Any suggestion is appreciated. Thanks for helping!

**Comment by escowles** [comment]
Maybe it would be better to use the `member_of_collection_ids` to load the collection Solrdocument instead of finding by title (there could be multiple collections with the same title):

```
collection = ::SolrDocument.find(@document.member_of_collection_ids.first)
```

**Comment by hweng** [comment]
Thanks @escowles. Yep, there is the "member_of_collection_ids_ssim" solr field which make the things easy!  I think I accidentally checked collection record and didn't find such field.
Thanks for your helping!
