### ISSUE TITLE
Manager user is not getting all expected dashboard and work review functionality

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyrax#853]
### Expected behavior

In my Hyku demo repo, in an admin set with one-step deposit workflow, the admin/admin set manager granted manager role to User X.  

When logged in and viewing the dashboard, under the Repository Contents menu, User X should see the Administrative Set section listed and the admin set for which they are a manager should be listed on the page.  User X should see the Collections and Works sections on that menu too, with works in the admin set in which they have manager role listed on the Works listing page. 

User X should also see the Tasks menu with the Review Submissions page.

User X should receive notifications for activity related to the admin set 

### Actual behavior

These are the things that are missing or wrong:
- In-review works in the admin set are not listed on Repository Contents > Works
- Tasks > Review Submissions is showing but no in-review works are listed as tasks
- User X cannot access Review and Approval panel on the in-review work page, and cannot take action. The show page only displays the “work is in review” flash message; there is no way to review and approve the work.

**Comment by hannahfrost** [comment]
FWIW the same user is not getting access to the default admin set for which they have Depositor role

**Comment by laritakr** [comment]
Regarding the issues listed: 
It's a bit unclear which might be hyku-related issues, so we need to fix the hyrax issues first and then get them working in Hyku.

- First issue is https://github.com/projecthydra-labs/hyrax/issues/855
- Second issue? Not sure what this is referring to... in-review works seem to appear correctly in Hyrax. 
- Third issue is apparently related to the users not getting read or edit authority to the works based on their workflow actions. See issue https://github.com/projecthydra-labs/hyrax/issues/920

**Comment by hannahfrost** [comment]
@laritakr @jcoyne This morning I retested and this is what I experienced in my Hyku demo repo:

As Admin, I assigned another user the role of Manager in the default admin set which has one-step mediated deposit workflow configured. My expectation was that the Manager should be able to review/approve a work deposited to the admin set (see cell G17 here: https://docs.google.com/spreadsheets/d/1TSZ8CUuq6puwzyJ1Av0aQ798FOQZgzhkn2jaDYyt118/edit#gid=0). 

But in my demo repo, the Manager cannot review/approve. Also the Manager does not see Admin Set on the dashboard menu, but should, and the default admin set would be expected to be listed on the page when that menu item is selected. 

Manager does see Works dashboard menu item, but does not see any works listed there, even those that have completed workflow.

Manager does see Collections dashboard menu item, but does not see the collection to which they have been granted explicit view/download rights, listed there.

I'm happy to express these as individual tickets if that makes sense. Have I stumbled on a combination of missing Manager role abilities as well as display bugs?

**Comment by laritakr** [comment]
@hannahfrost This would seem to me to be related to the fact that changing an admin set's participants does not apply the new permissions to works already in progress. Your new manager should be able to see, review or approve any NEW works submitted after the participant role has been granted, but adding a new manager does not retrofit permissions on all of the works already in the admin set.  

I am looking into the workflow and admin set permissions structure as part of the role permissions design work I'm doing, so it would be helpful to understand what all the needs are so I can take that into consideration.

In addition, the collections dashboard item only shows "user collections" I believe, not administrative collections. In your comments above, you seem to be referring to administrative collections, which from my knowledge are publicly accessible only via the main page. (I may be wrong in this, but that's the only place I've found them available in hyrax to anyone other than via the admin menu. I haven't checked Hyku recently to verify what all is different there).

**Comment by jcoyne** [comment]
@hannahfrost can you clarify what "cannot review/approve" means to you?  What are you seeing that leads you to believe that?

**Comment by hannahfrost** [comment]
@laritakr @jcoyne I'm going to record a screencast to show you what I am experiencing since my words alone aren't adequate. Stay tuned.

**Comment by jcoyne** [comment]
@hannahfrost I think individual tickets would be the most helpful as you've found lots of issues and we have questions about why each may or may not be an issue.

**Comment by mjgiarlo** [comment]
@jcoyne @laritakr OK, I went through and tried to reproduce what @hannahfrost found, and here's what I saw:

> In-review works in the admin set are not listed on Repository Contents > Works

This is still true. Ticketed as #965 and currently sitting in "design needed" column.

> Tasks > Review Submissions is showing but no in-review works are listed as tasks

This is no longer true.

> User X cannot access Review and Approval panel on the in-review work page, and cannot take action. The show page only displays the “work is in review” flash message; there is no way to review and approve the work.

This is no longer true.

Responding to more stuff from :point_up:, the Admin Set Manager does currently:

* See the Works menu
* See the Collections menu
* See the Review Submissions menu
* See works (from Admin Sets the user manages) that require approval in the Review Submissions page
* Receive notifications related to works moving through workflow in the Admin Sets they manage

So I'm thinking this issue should focus on:

* Admin Set Manager should see Admin Sets menu in dash
* Admin Sets page should include the Admin Sets the user is managing

Cool?

**Comment by laritakr** [comment]
@mjgiarlo makes sense to me.

**Comment by mjgiarlo** [comment]
OK. Closing for now. Pls re-open if I've done so in haste!

**Comment by hannahfrost** [comment]
Sounds good. Thanks, @mjgiarlo
