### ISSUE TITLE
fix odd wrapping in Save Work panel

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyrax#854]
The embargo date field and visibility selection menus are all mixed up with the displayed text due to poor alignment.

![screenshot 2017-04-28 05 54 13](https://cloud.githubusercontent.com/assets/1801076/25529900/ee58c60a-2bd8-11e7-93c9-a866587e6cbd.png)

**Comment by mjgiarlo** [comment]
@ggeisler Might you have time to take a look at this next week?

**Comment by ggeisler** [comment]
@mjgiarlo Sure, I'll try to get to it soon.

**Comment by mjgiarlo** [comment]
@ggeisler Thx!

**Comment by hannahfrost** [comment]
It appears similarly frightful on the file/fileset edit page, permissions tab.

![screenshot 2017-05-01 10 06 33](https://cloud.githubusercontent.com/assets/1801076/25586820/fe673070-2e55-11e7-9732-e24a0c55e0f7.png)

**Comment by ggeisler** [comment]
@hannahfrost The file edit page, permissions tab also has things other than the embargo settings that could use styling/layout improvement so I'm going to make a separate ticket for that.
