### ISSUE TITLE
Works in workflow should be listed with All Works

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyrax#855]
Works in active workflow (undergoing review) are not listed on the dashboard under Repository Contents > Works - All Works tab. They should be viewable to the repository admin on this tab, and filterable along with published works in the existing filter.

**Comment by jcoyne** [comment]
@hannahfrost @ggeisler Is there a mockup for this somewhere?

**Comment by ggeisler** [comment]
@jcoyne The general Works ticket includes a mockup of the All Works tab that has one work listed as "In review." See about 1/3 down the mockup description: https://github.com/projecthydra-labs/hyku/issues/447

The table for the All Works tab includes a column called "Status" so we can distinguish works that are published versus those in review, but that column is not currently in the table. The filters should also include a "Status" filter.

**Comment by jcoyne** [comment]
@ggeisler thanks.
