### ISSUE TITLE
Review Submissions page - works should be listed on the tabs as appropriate

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyrax#856]
Regardless of current workflow status, all works submitted in a review workflow are listed on the ‘Under Review’ tab. It is expected that works no longer in active workflow (no longer under review) would appear instead on the ‘Published’ tab on this page.

**Comment by laritakr** [comment]
I believe this issue belongs in Hyku? I don't think Hyrax includes the mentioned pages.

**Comment by jcoyne** [comment]
@hannahfrost I'm unable to duplicate this. Is it fixed?

Starting state:

<img width="1080" alt="screen shot 2017-05-11 at 12 33 10 pm" src="https://cloud.githubusercontent.com/assets/92044/25963252/4556aad6-3646-11e7-862e-c6d8f8d1f781.png">

Then, I review the work and when I come back to this page, it is off the "Under Review" tab:
<img width="1086" alt="screen shot 2017-05-11 at 12 34 00 pm" src="https://cloud.githubusercontent.com/assets/92044/25963269/55197cc8-3646-11e7-9e82-425d8acf8364.png">

And it is on the published tab:
<img width="1090" alt="screen shot 2017-05-11 at 12 34 07 pm" src="https://cloud.githubusercontent.com/assets/92044/25963278/5b77a7c0-3646-11e7-83f8-6b2f4a639029.png">

**Comment by hannahfrost** [comment]
@jcoyne It is not fixed. As Admin, I just approved a work and it stays listed on the "Under Review" tab

![screenshot 2017-05-11 10 51 13](https://cloud.githubusercontent.com/assets/1801076/25963907/dc3cae46-3637-11e7-9c2b-ffddaeb43936.png)
