### ISSUE TITLE
Depositor is not able to see or edit works in-review after submission

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyrax#857]
### Expected behavior

In my Hyku demo repo, in an admin set with one-step deposit workflow, the admin set manager granted the depositor role to User Y. User Y deposited a work to the admin set. After review, the work was returned to the depositor, User Y, for changes.  

User Y receives a notification about the request for changes. The link in the notification leads to the in-review page for the Work, where it should be possible for the depositor to edit the work and its files. 

When logged in and viewing the dashboard, under the Repository Contents menu, User Y should see the Collections and Works sections, with their deposited works in the admin set in which they have the depositor role listed on the Works page. And User Y should be able to edit an in-review work from the Works page

User Y should receive notifications for activity related to their works in an admin set 

### Actual behavior

These are the things that are wrong:
- User Y cannot see or take any action to edit the work (description, release/visibility, relationships, files) from the work view page (only accessible from link in notification)
- Works in the admin set are not listed on Repository Contents > Works while they are in-review

**Comment by laritakr** [comment]
The first issue that is wrong is https://github.com/projecthydra-labs/hyrax/issues/920
The second issue has to do with issue https://github.com/projecthydra-labs/hyrax/issues/855
