### ISSUE TITLE
Backport upstream fix to require Hyrax::Name to branch: 1-0-stable

### ISSUE THREAD

**Issue by afred** [projecthydra-labs/hyrax#858]
### Descriptive summary

Was getting this error: `app/models/concerns/hyrax/naming.rb:12:in `model_name': uninitialized constant Hyrax::Name (NameError)`.

This was fixed upstream (in `master`) with this commit: https://github.com/projecthydra-labs/hyrax/commit/f062a73c5d04901e13eaee88edff7ed7a838482e.

### Rationale

We need this fix in `1-0-stable` branch.

### Expected behavior

We no longer get the error when using `1-0-stable` branch.

### Actual behavior

We're getting the error in `1-0-stable` branch

### Steps to reproduce the behavior

We were getting it when we tried to run `bundle exec rspec spec` in our host application.

**Comment by mjgiarlo** [comment]
@afred I believe this should be closed. Can you confirm (and, if so, close)? Thanks!

**Comment by mjgiarlo** [comment]
Re-open if I've gotten this wrong, pls.
