### ISSUE TITLE
Epic: workflow bugs in 1.x

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra-labs/hyrax#872]
These are in Hyrax 1.0.0.rc1, based on testing done by @newmanld and others. @newmanld: do you consider any of these to be blockers for the 1.0.0 release? Could they be fixed in 1.0.1, for instance? Thanks!

@projecthydra-labs/hyrax-code-reviewers if someone might want to decompose these into separate tickets and begin verifying/troubleshooting, that would be grand.

**UPDATE: this has been divvied into the following tickets:**
  * #880
  * #881
  * #882
  * #884

**Comment by mjgiarlo** [comment]
Thank you, @afred!

**Comment by mjgiarlo** [comment]
@afred @newmanld @hortongn @hackmastera Three of the above four issues are now closed, with fixes available in the `1-0-stable` branch.

Might any of y'all have cycles to verify that the behavior has changed and now matches your expectations?

**Comment by newmanld** [comment]
Mike – we are doing our first ‘unveiling’ today of our IR on top of Sufia 7.3.  This is our beta preview expected to be about 30 days.  We plan to move our app to Hyrax, as well as of course adjust to the feedback we get from the Beta preview, next, with data migration over the summer.  Anyway, no bandwidth today or tomorrow to deploy Hyrax with these fixes and take another look, but I’ll ask that we do so next week. -- Linda

**Comment by newmanld** [comment]
@mjgiarlo I didn't answer your question about blockers.  I do consider these blockers but can't yet explain why you could not replicate the behavior I see in #882.

**Comment by mjgiarlo** [comment]
@newmanld Congrats! And thanks. :)
