### ISSUE TITLE
Improve layout/styling of File Edit, Permissions tab

### ISSUE THREAD

**Issue by ggeisler** [projecthydra-labs/hyrax#874]
![butterfly_jpg____file__6d56zw601_____hyrax](https://cloud.githubusercontent.com/assets/101482/25640176/82cb68c0-2f43-11e7-82c8-e7fd10a439be.png)

**Comment by mjgiarlo** [comment]
Hi, @ggeisler, I see you're assigned to this. Is this something you're actively working on?

**Comment by ggeisler** [comment]
Hi @mjgiarlo. Sort of. I looked at it last week to understand what needed to be done, but haven't had time to deal with it since then. (It needs fairly significant updates; the Share With section in particular is coded very oddly, with all that bolded text as part of the `h3` header.)

I'm trying to get back to HyBox for most of the rest of the week so could still get to it soon, but you could also remove me from it if you have other ideas.

**Comment by mjgiarlo** [comment]
Thanks, @ggeisler. I'm content to leave it in your hands. :) (Was just doing some waffle/github issue management.)
