### ISSUE TITLE
Automatically add 'registered' group to depositors of Default Admin Set

### ISSUE THREAD

**Issue by afred** [projecthydra-labs/hyrax#880]
### Descriptive summary

targeting v1.0.0

### Rationale

We do this in `master` and should consider backporting this work, else the sharing tab disappears and the relationships tab appears with no values in the Admin Set dropdown.

**Comment by jcoyne** [comment]
Fixed on master in https://github.com/projecthydra-labs/hyrax/pull/717

**Comment by mjgiarlo** [comment]
Fixed by https://github.com/projecthydra-labs/hyrax/pull/887
