### ISSUE TITLE
Adding one or more Admin Sets changes Default AS to being closed by default

### ISSUE THREAD

**Issue by afred** [projecthydra-labs/hyrax#881]
### Descriptive summary

targeting Hyrax v1.0.0

### Rationale

>  If as the administrative user I add a second administrative set (calling it here the ‘mediation administrative set’) and connect it to this one-step mediation workflow, and assign participants to the new mediation administrative set, and assign roles to workflows, users with either the deposit or approve mediation role are no longer able to deposit to the default administrative set, unless as the administrative user, I add them as participants (depositors) to the default administrative set.

Note: I'm not seeing this in `master` so this may be another bit of work that is backportable.

### Related work

**Comment by mjgiarlo** [comment]
I believe this will be irrelevant once #887 is merged.

**Comment by mjgiarlo** [comment]
Fixed by https://github.com/projecthydra-labs/hyrax/pull/887
