### ISSUE TITLE
Approval UI not appearing

### ISSUE THREAD

**Issue by afred** [projecthydra-labs/hyrax#882]
### Descriptive summary

targeting Hyrax v1.0.0

### Rationale

> I have authorized a user to be an approver in the mediation workflow – but they will not see anywhere in the GUI the ability to approve the work.  Only the repository administrator, if given the approver workflow role, can approve works.  This seems to be an omission?

As the approving user, I cannot navigate to the deposited work's show page and see the "Review and Approval" bar near the bottom of the window.

**Comment by mjgiarlo** [comment]
I could not reproduce this, @newmanld. 

@projecthydra-labs/hyrax-code-reviewers anyone else have cycles to spin up 1.0.0.rc1 and try to reproduce?

**Comment by jenlindner** [comment]
I'm doing some testing of this for DCE and seeing it also. So far no luck in granting a user the mediated deposit approval role, then logging in as them and seeing submissions show up under review submissions or the review UI tab in in the work itself. Still testing.

**Comment by jcoyne** [comment]
@jenlindner what commit are you testing on?

**Comment by jenlindner** [comment]
sorry @jcoyne didn't see your questions until now. we do a gem install from 1.0.0.rc1.

**Comment by jcoyne** [comment]
@jenlindner would you be able to retest with the latest from the 1-0-stable branch?

**Comment by jenlindner** [comment]
@jcoyne -- yeah, thanks, i'll get back to you on it.

**Comment by jenlindner** [comment]
Okay, here are the steps I took, using the 1-0-stable branch this time, and same results. 
- Sign up as new user1, try to deposit work, get error that permission template is missing. 
- Sign up as another user2. 
- Add an admin to the role_mapper.yml, restart web server.
- Sign in as that admin_user, get link to admin panel. 
- Go to admin panel, go to Workflows/Roles, 
- Choose user2 to grant a role to, click role dropdown and it's empty.

I'm going to test next spinning up again and logging in for the first time as admin, after adding the role to role_mapper.yml. I think I get different results (but still errors) that way.

**Comment by jenlindner** [comment]
Scenario Two, using the 1-0-stable branch: 
- Edit role_mapper to include an admin under development env.
- Sign up/in as that admin user
- sign up as new user, deposit work
- sign up as second new user
- sign in as admin, give second user approving role for mediated deposit and default
- sign in as second user, see nothing in UI indicating review capacity.

**Comment by jenlindner** [comment]
- Sign in as approving user, deposit work.
- work success page says work is pending review. my dashboard shows I deposited a work, and i have a notification that a work needs review.

**Comment by laritakr** [comment]
[My notes from testing workflows](https://gist.github.com/laritakr/3020bdd70609a7fc224078dca1871fd8)... three issues were found:

1) default authority does not give a basic user the ability to edit their own works.
2) workflow roles (in the dropdown list) do not include detail on which admin (I think?) set they relate to so it's hard to make the assignment correctly
  NOTE: I know this was changed, but apparently the change didn't make it into the stable branch?
3) non-admin users are not able to approve private works. only admin users can approve all works.

**Comment by jcoyne** [comment]
@laritakr can you create those as issues?

Regarding the first, I think that's intentional at least for the mediated deposit workflow.  Once a work is submitted, it shouldn't be changed.  For the single step workflow, there is an action that gives the depositor edit access https://github.com/projecthydra-labs/hyrax/blob/master/lib/generators/hyrax/templates/workflow.json.erb#L14

**Comment by jcoyne** [comment]
@jenlindner can you convert these steps into a failing feature spec?

**Comment by laritakr** [comment]
I should note that I believe the original issue that @afred is reporting is that only the admin user has the review submissions menu. I found ways around that, but I did not address his initial point that perhaps someone with reviewing access should also see that menu somewhere?

**Comment by laritakr** [comment]
This issue has been broken down into the three separate issues.

**Comment by afred** [comment]
See #908, #910, #920.
