### ISSUE TITLE
Share tab disappearing

### ISSUE THREAD

**Issue by afred** [projecthydra-labs/hyrax#884]
### Descriptive summary

targeting Hyrax v1.0.0

### Rationale

> Also, please see @hortongn's comment on this same thread from 4/24.  We found (with @hackmastera's help) that the `allow_access_grant` workflow setting would make the share tab show up for both work creation and editing, for someone depositing to the default admin set with default workflow, in Sufia 7.3.  We assume, but haven't tested yet, if the same workflow setting solves the same problem in Hyrax 1.0.

### Related work

**Comment by jcoyne** [comment]
Possible fix from master: https://github.com/projecthydra-labs/hyrax/pull/719

**Comment by mjgiarlo** [comment]
Fixed by #888.
