### ISSUE TITLE
Workflow roles in dropdown are not unique

### ISSUE THREAD

**Issue by laritakr** [projecthydra-labs/hyrax#908]
### Descriptive summary

Hyrax 1-0-Stable branch workflow roles dropdown does not include the change that exists in the master branch which shows what admin set the workflow belongs to.

I believe this may have been fixed in https://github.com/projecthydra-labs/hyrax/pull/689/files

### Rationale

Without this change, there is no way to be certain that a user is being given access to the appropriate workflow role.

### Expected behavior

The workflow roles dropdown should have unique titles in the list, clearly identifying their admin set.

### Actual behavior

![screen shot 2017-05-05 at 1 38 38 pm](https://cloud.githubusercontent.com/assets/17851674/25757391/483ee856-3198-11e7-96c7-7479967a7cb9.png)

### Steps to reproduce the behavior

[The gist shows the steps I took, with the highlighted line indicating the point when the issue was reached.](https://gist.github.com/laritakr/3020bdd70609a7fc224078dca1871fd8#file-gistfile1-txt-L34)

### Related work

https://github.com/projecthydra-labs/hyrax/issues/882

**Comment by laritakr** [comment]
This work was previously done. The changes need to be located and incorporated into this branch. The link in the description MAY be the right one, but I haven't checked for sure.

**Comment by mark-dce** [comment]
Marking this as a blocker for 1.0.0 since the original ticket this replaced was identified that way.  

Beyond that history, the current dropdown is completely ambiguous in any situation with more than one admin set (i.e. the user has no way of knowing which admin_set + workflow they are actually granting access to).

**Comment by mjgiarlo** [comment]
Agreed that a backport should fix this.
