### ISSUE TITLE
Non-admin reviewers need to be able to review all works in their admin set

### ISSUE THREAD

**Issue by laritakr** [projecthydra-labs/hyrax#910]
### Descriptive summary

Hyrax 1-0-Stable branch workflow process does not give a non-admin user the ability to approve anything other than public works.

It is possible that there is a way to manage this that I didn't find (through permissions on the admin set perhaps?) but if so, the steps need to be clearly documented, and a user should not be allowed to be assigned the reviewer role without the correct permissions. 

### Rationale

Only the admin user has the review submissions menu. Other users with the approving role can only approve by clicking the link to the work in the notifications.  I don't know whether the review submissions menu allows the approving role to have access to view works they are otherwise not authorized to see, but they definitely can't access them via the link in the notification.

### Expected behavior

If a user has the approving role, they should be able to view and approve the work.

### Actual behavior

The user cannot view or review a work unless it is public.
[Spreadsheet of details from testing of workflows](https://docs.google.com/spreadsheets/d/1zQsWlYMVs7gz6dHaOiXICygLj_5GTFOmbpI9MHRAq5o/edit#gid=0) on both stable and master branches. 

### Steps to reproduce the behavior

[The gist shows the steps taken, and the highlighted line shows the point where this issue was reached.](https://gist.github.com/laritakr/3020bdd70609a7fc224078dca1871fd8#file-gistfile1-txt-L50)

### Related work

https://github.com/projecthydra-labs/hyrax/issues/882

**Comment by laritakr** [comment]
Need to add the ability to grant "read" authority according to workflow state.

**Comment by mark-dce** [comment]
@laritakr I was just going to mark this as a blocker based on our use cases, is there a reason you removed the blocker label?  I would be in support of keeping it.

**Comment by laritakr** [comment]
@mark-dce I had originally set it as a blocker, but . I removed it because I am evaluating the behavior in more detail, and working to identify all of the issues and determine if there are workarounds.

At that point, I assumed we would determine for sure what all of the blockers are. But yes, I'm fine with calling it a blocker for now since I haven't finished that analysis yet. I'll replace the tag.

**Comment by laritakr** [comment]
In the master branch, reviewers are able to review private works if they also were assigned the "viewer" role. There should be some changes in master which can be ported to the 1-0-Stable branch to make this workable.

**Comment by mjgiarlo** [comment]
This is related to https://github.com/projecthydra-labs/hyrax/pull/761, which has gone cold.

**Comment by mjgiarlo** [comment]
I'm trying to unstick #761. Pushed a small change and created a new issue about a potential redesign based on what @jeremyf suggested. Hoping we can get this change in soon and revisit the latter thereafter.
