### ISSUE TITLE
Visibility options for Embargo don't expand on batch create form

### ISSUE THREAD

**Issue by hortongn** [projecthydra-labs/hyrax#930]
### Descriptive summary

When a user is on the batch create form and clicks the radio button for "Embargo" the form does not expand to reveal the "Restricted to..." or "then open it up to.." options like it does on the single work form.  

We experienced the bug on 1.0.0.rc1, but it looks like the bug is still in master as well.

### Expected behavior

Clicking on the "Embargo" radio button in the Visibility section of the batch create form should reveal additional form options.

### Actual behavior

Clicking on the "Embargo" radio button in the Visibility section of the batch create form has no effect other than selecting the radio button itself.

### Steps to reproduce the behavior

1. Go to the form to create a new batch work
1. Click on the "Embargo" radio button

### Related work

University of Cincinnati has fixed this locally here: https://github.com/uclibs/scholar_uc/pull/1373/files

The problem is that the batch form doesn't include the `data-behavior="work-form"` in the <form> tag.  So the JS that expands the options doesn't know what to act on.

**Comment by mjgiarlo** [comment]
@hortongn What tag/branch/commit are you seeing this with?

Thanks for reporting this, and for linking to your fix!

**Comment by hortongn** [comment]
@mjgiarlo I've updated the bug description with the version we were using.

**Comment by mjgiarlo** [comment]
Thanks for taking this on, @hortongn!
