### ISSUE TITLE
Browse everything only attaches files on work create (not edit)

### ISSUE THREAD

**Issue by hortongn** [projecthydra-labs/hyrax#931]
### Descriptive summary

Attaching cloud files to a work behaves as expected when creating a brand new work.  However, if an existing work is edited and the user attempts attach cloud-based files, and exception is thrown upon saving the work.  Files are not attached.

We experienced the bug on 1.0.0.rc1, but it looks like the bug is still in master as well.

### Expected behavior

The user should be able to attach cloud files either when creating a work or editing a work.

### Actual behavior

Editing and saving an existing work with new cloud-based files attached throws an error.

### Steps to reproduce the behavior

1. Create a work
1. Edit the work
1. Add some new files from a cloud provider
1. Save the work

### Related work

University of Cincinnati has fixed this locally here: 
https://github.com/uclibs/scholar_uc/pull/1371/files

The fix is in the last line of the partial.

The problem is that when editing a work, browse_everything is looking for a form id of `edit_generic_work`. However the actual form id has the pid attached (e.g. `edit_generic_work_h989r335q`)

**Comment by mjgiarlo** [comment]
@hortongn Thanks! Which Hyrax tag/branch/commit did you see this with?

**Comment by hortongn** [comment]
@mjgiarlo I've updated the bug description with the version we were using.
