### ISSUE TITLE
Embedded video player not working

### ISSUE THREAD

**Issue by hortongn** [projecthydra-labs/hyrax#932]
### Descriptive summary

When a video file is attached to a work, the file show page embeds an HTML5 video player.  However, the player never loads the video.

### Expected behavior

The file show page for videos should allow the user to play the video right on the page.

### Actual behavior

The video player remains empty. 

### Steps to reproduce the behavior

1. Create a work and attach a video
1. Save the work and go to the file's show page
1. The video never loads in the player

### Related work

University of Cincinnati has fixed this locally here: 
https://github.com/uclibs/scholar_uc/pull/1353/files

The PR addresses two problems:
1. loads the file properly into the player
1. restricts the size of the player so it doesn't automatically expand to a much larger size when the source video is large.

Note: it can take a bit a time for the video to eventually show up in the player.  Be patient.

**Comment by mjgiarlo** [comment]
@hortongn I'm guessing this affects both 1.x and 2.x.

**Comment by jcoyne** [comment]
It looks like the fix UC is using is streaming the original file and not the pregenerated derivatives

**Comment by hortongn** [comment]
Hmm, should Hyrax/Sufia be automatically generating video derivatives for us?  The embedded audio player works fine for us out of the box, but the video player didn't work when trying to use derivatives.

**Comment by mjgiarlo** [comment]
@hortongn there are config options to enable ffmpeg transcoding. (I haven't personally tested those in Hyrax yet, admittedly.)

**Comment by jcoyne** [comment]
@hortongn Yes, it should be making derivatives, but I think there is a bug in the view. I think this code never got updated when the derivatives moved from being persisted in Fedora to being on the file system.

**Comment by jcoyne** [comment]
This is working fine for me.  Perhaps your ffmpeg isn't enabled or configured correctly? FWIW, for a FileSet with id `6682x392q` I'm seeing these files:
```
tmp/derivatives/66/82/x3/92/q-mp4.mp4
tmp/derivatives/66/82/x3/92/q-thumbnail.jpeg
tmp/derivatives/66/82/x3/92/q-webm.webm
```

and this generated html:
```html
<video controls="controls" class="video-js vjs-default-skin" data-setup="{}" preload="auto">
    <source src="/downloads/6682x392q?file=webm&amp;locale=en" type="video/webm">
    <source src="/downloads/6682x392q?file=mp4&amp;locale=en" type="video/mp4">
    Your browser does not support the video tag.
  </video>
```

**Comment by hortongn** [comment]
@jcoyne Thanks  I'm thinking https://github.com/projecthydra-labs/hyrax/pull/940 you just opened helps clear this up.  I assumed ffmpeg would be creating derivatives by default.  If the default for config.enable_ffmpeg is `false` then we need to enable it.  

We definitely have ffmpeg installed correctly.  Since embedded audio is working, we assumed ffmpeg was doing what it needed for videos as well.

I'll enable the config option and will report back here on what I'm seeing.

**Comment by hortongn** [comment]
Enabling ffmpeg derivatives does fix the embedded player for us without any tweaks needed in the view.  So I'm closing this issue.  No fix is needed.  Thanks @jcoyne
