### ISSUE TITLE
Deprecation warning in tests

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyrax#971]
This change: 
https://github.com/projecthydra-labs/hyrax/commit/3f1b58195d4381c51fde8b9149016c5b09f0c9b4#diff-0090d222225596fb0c42c854d80d03c0R126

Causes the deprecation:

```
DEPRECATION WARNING: You are passing an instance of ActiveRecord::Base to `find`. Please pass the id of the object by calling `.id`. (called from uploaded_files at /Users/jcoyne/workspace/hyrax/app/actors/hyrax/actors/create_with_files_actor.rb:50)
```

The value used to be an integer and now it's a `Hyrax::UploadedFile`

**Comment by mjgiarlo** [comment]
I started taking a look at this and very soon after got lost in the actor stack. I didn't see the deprecation warning locally, FWIW, not that I doubt you.

**Comment by jcoyne** [comment]
@mjgiarlo `rspec ./spec/actors/hyrax/actors/generic_work_actor_spec.rb:142` should trigger it.
