### ISSUE TITLE
Selecting new thumbnail should enable save button in file manager

### ISSUE THREAD

**Issue by andjsmit** [projecthydra-labs/hyrax#979]
### Descriptive summary

When changing a file set's Thumbnail or Representative Media, the save button does not enable as it should. The save button does enable as expected when the order of the files in a file set are changes. This behavior was seen in both Firefox and Chrome for the Master branch.

### Rationale

Without the Save button being enabled, it is not possible to save the newly selected thumbnail.

### Expected behavior

Upon selecting a new Thumbnail, the save button should be enabled.

### Actual behavior

Save button remains disabled.

### Steps to reproduce the behavior

1. Create a file set with more than one image
1. Go to the file manager fro the item
1. Change the selected thumbnail.
1. Save button remains disabled.

![file_manager_no_save](https://cloud.githubusercontent.com/assets/333335/26118502/29b1e75a-3a38-11e7-9ce5-1c8aeae5b9ca.png)

**Comment by tpendragon** [comment]
Interesting - this used to work.

**Comment by atz** [comment]
Unable to reproduce.  Seems fixed to me:
![screen shot 2017-05-23 at 2 54 33 pm](https://cloud.githubusercontent.com/assets/109954/26378121/f7ef611c-3fc7-11e7-9048-8e67a3f1c6d2.png)

**Comment by jcoyne** [comment]
@atz Possibly one of the fixes in #1001 fixed it.

**Comment by atz** [comment]
Please reopen if we se it again...

**Comment by hannahfrost** [comment]
@atz I saw this same issue two more times in testing today, where the save button become enabled after a radio button selection change, but cannot reproduce it in a predictable way. Just noting that here; will reopen when I can reliably reproduce.
