### ISSUE TITLE
One should be able define any workflow as the default workflow

### ISSUE THREAD

**Issue by vantuyls** [projecthydra-labs/hyrax#98]
### Descriptive summary

We have a number of use cases for defining a default workflow for a hyrax repository as other than the current default, zero-step workflow. One (repository administrator?) should be able to define the default workflow as suits the use case for that repository. 

Example, my preferred default workflow, for when anyone deposits content into the repository but not into an admin set, is that there be a one-step mediation process. I should be able to set the default workflow as such. 

@scholarworks

**Comment by mjgiarlo** [comment]
@vantuyls @scholarworks I believe this is already possible by editing the Default Admin Set, assuming the behavior in #237 has already been triggered. If I'm wrong about that, feel free to re-open!
