### ISSUE TITLE
Remove admin group from sharing section of collection form

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra-labs/hyrax#996]
Check the work form for the same.

<img width="1005" alt="screen shot 2017-05-22 at 1 56 35 pm" src="https://cloud.githubusercontent.com/assets/92044/26324002/9e0aa94e-3ef6-11e7-8392-fb81e2e1283e.png">

**Comment by darrenleeweber** [comment]
Where is the `sharing` code?  It's not obvious in:
- https://github.com/projecthydra-labs/hyrax/blob/master/app/forms/hyrax/forms/collection_form.rb
- https://github.com/projecthydra-labs/hyrax/blob/master/app/forms/hyrax/forms/work_form.rb

**Comment by darrenleeweber** [comment]
May also need some background on how the admin-group is added to the sharing section of a collection/work and whether this happens automatically or not.  If it is automatic, is the admin-group stored in a static field of the ActiveRecord object or is it a dynamic addition that follows some access rules in the code somewhere?

**Comment by darrenleeweber** [comment]
Once a collection is created, the show collection page does not include any sharing information when the collection was created without any sharing options
- example collection show URL:  http://localhost:3000/collections/cf95jb44s?locale=en,

**Comment by darrenleeweber** [comment]
`git grep "Share work with groups"` returns:
- app/views/hyrax/base/_form_share.html.erb:<h2>Share work with groups of users</h2>
- app/views/hyrax/collections/_form_share.html.erb:  <h4>Share work with groups of users</h4>

**Comment by darrenleeweber** [comment]
Confirmed that when a `user.ability.admin? => true` user is logged in and creates a new collection, the sharing drop-down selector does contain the `admin` group, that is:

`Share work with groups of users` -> `Select a group` drop-down contains an `admin` entry.

**Comment by jcoyne** [comment]
I wonder if this is okay to leave as is. It seemed odd that there was an admin group, but not really that odd if only admins will see it.

**Comment by mjgiarlo** [comment]
@darrenleeweber Let's hold off on making any more changes to this issue or the related PR, and we'll discuss on stand-up today. (Relaying this from slack.)

**Comment by darrenleeweber** [comment]
At standup today, we discussed this and concluded that the existing behavior is good; the admin group does not need to be treated as a special group to be excluded from sharing.
