### ISSUE TITLE
Spaces in the "part_of" property throw an RSolr Error

### ISSUE THREAD

**Issue by aaron-collier** [projecthydra-labs/hyrax#998]
### Descriptive summary

When the data for the `part_of` property has spaces in it, the following RSolr error is thrown:

Data in field: `[epub ahead of print];`

```RSolr::Error::Http: RSolr::Error::Http - 400 Bad Request
Error: 'no field name specified in query and no default specified via \'df\' param','code'=>400}}

URI: http://127.0.0.1:8983/solr/hydra-development/select?wt=ruby&rows=1&sort=system_create_dtsi+asc&fl=id&q=_query_%3A%22%7B%21raw+f%3Dhas_model_ssim%7DAdminSet%22+AND+%28%7B%21terms+f%3Did%7D%5Bepub+ahead+of+print%5D%29&qt=standard&start=0&rows=1000
```

### Expected behavior

This data isn't always a URL/URI and often is describing something about the resource as to it's relationship to a part of a series. Spaces should be allowed.

**Comment by jcoyne** [comment]
@aaron-collier how do I reproduce this problem?

**Comment by aaron-collier** [comment]
@jcoyne I'll update with steps to do this in the UI. I'm hitting it when importing, but will try it in the UI.

Is the `part_of` property being used for `AdminSet` membership? the solr query above is looking for an `AdminSet` with the data in the property.

**Comment by jcoyne** [comment]
@aaron-collier no, `part_of` is defined in the `BasicMetadata`

**Comment by jcoyne** [comment]
@aaron-collier as far as I can tell, we define a `part_of` metadata property, but never actually use it in the UI.

**Comment by jcoyne** [comment]
@aaron-collier as far as I can tell, we define a `part_of` metadata property, but never actually use it in the UI.

**Comment by aaron-collier** [comment]
@jcoyne yeah - that seems to be what I'm seeing, but the solr query above seems to be looking for an AdminSet with the data that's in the field... Odd.

**Comment by aaron-collier** [comment]
See the comment:

cjcolvar [1:22 PM] 
@acollier I think I’m finally getting it now….basic metadata part_of is conflicting with the admin_set association as they are both using DC.isPartOf:
app/models/concerns/hyrax/basic_metadata.rb:      property :part_of, predicate: ::rdf::Vocab::DC.isPartOf
app/models/concerns/hyrax/in_admin_set.rb:      belongs_to :admin_set, predicate: ::rdf::Vocab::DC.isPartOf
